import { IFilterCheckboxItem } from '@/types/catalog'

// Категорія
export const category = [
  { checked: false, id: '1', title: 'Легкові автомобілі', event: '' },
  { checked: false, id: '2', title: 'Вантажні автомобілі', event: '' },
  { checked: false, id: '3', title: 'Автобуси', event: '' },
  { checked: false, id: '4', title: 'Мото', event: '' },
  { checked: false, id: '5', title: 'Інший транспорт', event: '' },
]

// Виробник
export const subcategory = [
  { checked: false, id: '1', title: 'Acura', event: '' },
  { checked: false, id: '2', title: 'Alfa Romeo', event: '' },
  { checked: false, id: '3', title: 'Aston Martin', event: '' },
  { checked: false, id: '4', title: 'Audi', event: '' },
  { checked: false, id: '5', title: 'Bentley', event: '' },
  { checked: false, id: '6', title: 'BMW', event: '' },
  { checked: false, id: '7', title: 'Buick', event: '' },
  { checked: false, id: '8', title: 'Cadillac', event: '' },
  { checked: false, id: '9', title: 'Chana', event: '' },
  { checked: false, id: '10', title: 'Chery', event: '' },
  { checked: false, id: '11', title: 'Chevrolet', event: '' },
  { checked: false, id: '12', title: 'Chrysler', event: '' },
  { checked: false, id: '13', title: 'Citroen', event: '' },
  { checked: false, id: '14', title: 'Dacia', event: '' },
  { checked: false, id: '15', title: 'Daewoo', event: '' },
  { checked: false, id: '16', title: 'Dodge', event: '' },
  { checked: false, id: '17', title: 'Ferrari', event: '' },
  { checked: false, id: '18', title: 'Fiat', event: '' },
  { checked: false, id: '19', title: 'Ford', event: '' },
  { checked: false, id: '20', title: 'Geely', event: '' },
  { checked: false, id: '21', title: 'Honda', event: '' },
  { checked: false, id: '22', title: 'Hummer', event: '' },
  { checked: false, id: '23', title: 'Huyndai', event: '' },
  { checked: false, id: '24', title: 'Infinity', event: '' },
  { checked: false, id: '25', title: 'Jaguar', event: '' },
  { checked: false, id: '26', title: 'Jeep', event: '' },
  { checked: false, id: '27', title: 'Kia', event: '' },
  { checked: false, id: '28', title: 'Lamborghini', event: '' },
  { checked: false, id: '29', title: 'Land Rover', event: '' },
  { checked: false, id: '30', title: 'Lexus', event: '' },
  { checked: false, id: '31', title: 'Lifan', event: '' },
  { checked: false, id: '32', title: 'Lincoln', event: '' },
  { checked: false, id: '33', title: 'Maserati', event: '' },
  { checked: false, id: '34', title: 'Maybach', event: '' },
  { checked: false, id: '35', title: 'Mazda', event: '' },
  { checked: false, id: '36', title: 'McLaren', event: '' },
  { checked: false, id: '37', title: 'Mercedes-Menz', event: '' },
  { checked: false, id: '38', title: 'Mitsubishi', event: '' },
  { checked: false, id: '39', title: 'Nissan', event: '' },
  { checked: false, id: '40', title: 'Opel', event: '' },
  { checked: false, id: '41', title: 'Peugeot', event: '' },
  { checked: false, id: '42', title: 'Porsche', event: '' },
  { checked: false, id: '43', title: 'Renault', event: '' },
  { checked: false, id: '44', title: 'Rolls-Royse', event: '' },
  { checked: false, id: '45', title: 'Rover', event: '' },
  { checked: false, id: '46', title: 'Skoda', event: '' },
  { checked: false, id: '47', title: 'Subaru', event: '' },
  { checked: false, id: '48', title: 'Suzuki', event: '' },
  { checked: false, id: '49', title: 'Tesla', event: '' },
  { checked: false, id: '50', title: 'Toyota', event: '' },
  { checked: false, id: '51', title: 'Volkswagen', event: '' },
  { checked: false, id: '52', title: 'Volvo', event: '' },
  { checked: false, id: '53', title: 'Інші', event: '' },
]

// Тип автомобіля
export const carType = [
  { checked: false, id: '1', title: 'З пробігом', event: '' },
  { checked: false, id: '2', title: 'Новий', event: '' },
  { checked: false, id: '3', title: 'Під пригон (авто не в Україні)', event: '' },
]

// Коробка передач
export const gearbox = [
  { checked: false, id: '1', title: 'Механічна', event: '' },
  { checked: false, id: '2', title: 'Автоматична', event: '' },
  { checked: false, id: '3', title: 'Варіатор', event: '' },
  { checked: false, id: '4', title: 'Адаптивна', event: '' },
  { checked: false, id: '5', title: 'Типтронік', event: '' },
]

// Тип палива
export const fuelType = [
  { checked: false, id: '1', title: 'Бензин', event: '' },
  { checked: false, id: '2', title: 'Дизель', event: '' },
  { checked: false, id: '3', title: 'Газ / бензин', event: '' },
  { checked: false, id: '4', title: 'Електро', event: '' },
  { checked: false, id: '5', title: 'Гібрид', event: '' },
  { checked: false, id: '6', title: 'Інший', event: '' },
]

// Тип кузова
export const carBodyType = [
  { checked: false, id: '1', title: 'Кабріолет', event: '' },
  { checked: false, id: '2', title: 'Пікап', event: '' },
  { checked: false, id: '3', title: 'Купе', event: '' },
  { checked: false, id: '4', title: 'Універсал', event: '' },
  { checked: false, id: '5', title: 'Хетчбек', event: '' },
  { checked: false, id: '6', title: 'Мінівен', event: '' },
  { checked: false, id: '7', title: 'Позашляховик / Кроссовер', event: '' },
  { checked: false, id: '8', title: 'Седан', event: '' },
  { checked: false, id: '9', title: 'Ліфтбек', event: '' },
  { checked: false, id: '10', title: 'Лімузин', event: '' },
  { checked: false, id: '11', title: 'Інший', event: '' },
]

// Кількість місць
export const seatsCount = [
  { checked: false, id: '1', title: '2', event: '' },
  { checked: false, id: '2', title: '3', event: '' },
  { checked: false, id: '3', title: '4', event: '' },
  { checked: false, id: '4', title: '5', event: '' },
  { checked: false, id: '5', title: '6', event: '' },
  { checked: false, id: '6', title: '7', event: '' },
  { checked: false, id: '7', title: '8 і більше', event: '' },
]

// Тип приводу
export const driveType = [
  { checked: false, id: '1', title: 'Повний', event: '' },
  { checked: false, id: '2', title: 'Передній', event: '' },
  { checked: false, id: '3', title: 'Задній', event: '' },
]

// Об'єм двигуна
export const engineVolume = [
  { checked: false, id: '1', title: '1 л.', event: '' },
  { checked: false, id: '2', title: '2 л.', event: '' },
  { checked: false, id: '3', title: '3 л.', event: '' },
  { checked: false, id: '4', title: '5 л.', event: '' },
  { checked: false, id: '5', title: '7 л.', event: '' },
]

// Колір
export const color = [
  { checked: false, id: '1', title: 'Білий', event: '' },
  { checked: false, id: '2', title: 'Чорний', event: '' },
  { checked: false, id: '3', title: 'Синій', event: '' },
  { checked: false, id: '4', title: 'Сірий', event: '' },
  { checked: false, id: '5', title: 'Сріблястий', event: '' },
  { checked: false, id: '6', title: 'Червоний', event: '' },
  { checked: false, id: '7', title: 'Зелений', event: '' },
  { checked: false, id: '8', title: 'Бежевий', event: '' },
  { checked: false, id: '9', title: 'Бірюзовий', event: '' },
  { checked: false, id: '10', title: 'Бронзовий', event: '' },
  { checked: false, id: '11', title: 'Вишневий', event: '' },
  { checked: false, id: '12', title: 'Блакитний', event: '' },
  { checked: false, id: '13', title: 'Жовтий', event: '' },
  { checked: false, id: '14', title: 'Золотистий', event: '' },
  { checked: false, id: '15', title: 'Коричневий', event: '' },
  { checked: false, id: '16', title: 'Матовий', event: '' },
  { checked: false, id: '17', title: 'Оливковий', event: '' },
  { checked: false, id: '18', title: 'Рожевий', event: '' },
  { checked: false, id: '19', title: 'Фіолетовий', event: '' },
  { checked: false, id: '20', title: 'Інший', event: '' },
] as unknown as IFilterCheckboxItem[]

// Лакове покриття
export const varnishCoating = [
  { checked: false, id: '1', title: 'Як нове, без видимих слідів експлуатації', event: '' },
  { checked: false, id: '2', title: 'Професійно відремонтоварі сліди експлуатації', event: '' },
  { checked: false, id: '3', title: 'Незначні сліди експлуатації (дрібні подряпини, сколи)', event: '' },
  { checked: false, id: '4', title: "Не відремонтовані сліди експлуатації (подряпини, вм'ятини і т.д.)", event: '' },
  { checked: false, id: '5', title: 'Потрібно відновлення (фарбування, заміна деталей, зварювання)', event: '' },
] as unknown as IFilterCheckboxItem[]

// Технічний стан
export const technicalCondition = [
  { checked: false, id: '1', title: 'На ходу, технічно справна', event: '' },
  { checked: false, id: '2', title: 'Не бита', event: '' },
  { checked: false, id: '3', title: 'Не пофарбована', event: '' },
  { checked: false, id: '4', title: 'Гаражне зберігання', event: '' },
  { checked: false, id: '5', title: 'Перший власник', event: '' },
  { checked: false, id: '6', title: 'Сервісна книжка', event: '' },
  { checked: false, id: '7', title: 'Потребує кузовного ремонту', event: '' },
  { checked: false, id: '8', title: 'Потребує ремонту ходової', event: '' },
  { checked: false, id: '9', title: 'Потребує ремонту двигуна', event: '' },
  { checked: false, id: '10', title: 'Після ДТП', event: '' },
  { checked: false, id: '11', title: 'Не на ходу', event: '' },
] as unknown as IFilterCheckboxItem[]

// Комфорт
export const comfort = [
  { checked: false, id: '1', title: 'Електропакет', event: '' },
  { checked: false, id: '2', title: 'Електросклопідйомники', event: '' },
  { checked: false, id: '3', title: 'Кондиціонер', event: '' },
  { checked: false, id: '4', title: 'Парктроник', event: '' },
  { checked: false, id: '5', title: "Бортовий комп'ютер", event: '' },
  { checked: false, id: '6', title: 'Датчик світла', event: '' },
  { checked: false, id: '7', title: 'Запуск кнопкою', event: '' },
  { checked: false, id: '8', title: 'Клімат контроль', event: '' },
  { checked: false, id: '9', title: 'Шкіряний салон', event: '' },
  { checked: false, id: '10', title: 'Круїз контроль', event: '' },
  { checked: false, id: '11', title: 'Люк', event: '' },
  { checked: false, id: '12', title: 'Панорамний дах', event: '' },
  { checked: false, id: '13', title: 'Ел. регулювання сидінь', event: '' },
  { checked: false, id: '14', title: 'Камера заднього виду', event: '' },
  { checked: false, id: '15', title: 'Передня камера', event: '' },
  { checked: false, id: '16', title: 'Мультируль', event: '' },
  { checked: false, id: '17', title: 'Омивач фар', event: '' },
  { checked: false, id: '18', title: 'Підігрів дзеркал', event: '' },
  { checked: false, id: '19', title: 'Обігрів керма', event: '' },
  { checked: false, id: '20', title: 'Підсилювач керма', event: '' },
  { checked: false, id: '21', title: 'Підігрів сидінь', event: '' },
  { checked: false, id: '22', title: 'Тонування скла', event: '' },
  { checked: false, id: '23', title: "Пам'ять сидінь", event: '' },
  { checked: false, id: '24', title: 'Датчик дощу', event: '' },
  { checked: false, id: '25', title: 'Алькантара', event: '' },
] as unknown as IFilterCheckboxItem[]

// Мультимедіа (
export const multimedia = [
  { checked: false, id: '1', title: 'CD', event: '' },
  { checked: false, id: '2', title: 'AUX', event: '' },
  { checked: false, id: '3', title: 'Bluetooth', event: '' },
  { checked: false, id: '4', title: 'USB', event: '' },
  { checked: false, id: '5', title: 'Акустика', event: '' },
  { checked: false, id: '6', title: 'Магнітола', event: '' },
  { checked: false, id: '7', title: 'Підсилювач', event: '' },
  { checked: false, id: '8', title: 'Сабвуфер', event: '' },
  { checked: false, id: '9', title: 'Система навігації GPS', event: '' },
  { checked: false, id: '10', title: 'Apple CarPay', event: '' },
  { checked: false, id: '11', title: 'Android Auto', event: '' },
]

// Безпека
export const security = [
  { checked: false, id: '1', title: 'ABD', event: '' },
  { checked: false, id: '2', title: 'ABS', event: '' },
  { checked: false, id: '3', title: 'ESP', event: '' },
  { checked: false, id: '4', title: 'Броньований автомобіль', event: '' },
  { checked: false, id: '5', title: 'Галогенні фари', event: '' },
  { checked: false, id: '6', title: 'Замок на КПП', event: '' },
  { checked: false, id: '7', title: 'Іммобілайзер', event: '' },
  { checked: false, id: '8', title: 'Пневмопідвіска', event: '' },
  { checked: false, id: '9', title: 'Подушка безпеки (Airbag)', event: '' },
  { checked: false, id: '10', title: 'Сервокермо', event: '' },
  { checked: false, id: '11', title: 'Сигналізація', event: '' },
  { checked: false, id: '12', title: 'Центральний замок', event: '' },
  { checked: false, id: '13', title: 'LED фари', event: '' },
  { checked: false, id: '14', title: 'Лазерні фари', event: '' },
  { checked: false, id: '15', title: 'Кснон', event: '' },
  { checked: false, id: '16', title: 'Денні ходові вогні', event: '' },
  { checked: false, id: '17', title: 'GPS трекер', event: '' },
  { checked: false, id: '18', title: 'Безключовий доступ', event: '' },
]

// Розмитнена
export const сustomsСleared = [
  { checked: false, id: '1', title: 'Так', event: '' },
  { checked: false, id: '2', title: 'Ні', event: '' },
  { checked: false, id: '3', title: 'Розмитнення "під ключ"', event: '' },
]

// Авто пригнано з
export const theCarWasDrivenFrom = [
  { checked: false, id: '1', title: 'США', event: '' },
  { checked: false, id: '2', title: 'Німеччина', event: '' },
  { checked: false, id: '3', title: 'Литва', event: '' },
  { checked: false, id: '4', title: 'Грузія', event: '' },
  { checked: false, id: '5', title: 'Корея', event: '' },
  { checked: false, id: '6', title: 'Польша', event: '' },
  { checked: false, id: '7', title: 'Швейцарія', event: '' },
  { checked: false, id: '8', title: 'Норвегія', event: '' },
  { checked: false, id: '9', title: 'Франція', event: '' },
  { checked: false, id: '10', title: 'Молдова', event: '' },
  { checked: false, id: '11', title: 'Іспанія', event: '' },
  { checked: false, id: '12', title: 'Італія', event: '' },
  { checked: false, id: '13', title: 'Португалія', event: '' },
  { checked: false, id: '14', title: 'Нідерланди', event: '' },
  { checked: false, id: '15', title: 'Бельгія', event: '' },
  { checked: false, id: '16', title: 'Латвія', event: '' },
  { checked: false, id: '16', title: 'Інша країна', event: '' },
]

export const filters = [
  { label: 'Категорія', items: category },
  { label: 'Виробник', items: subcategory },
  { label: 'Тип автомобіля', items: carType },
  { label: 'Коробка передач', items: gearbox },
  { label: 'Тип палива', items: fuelType },
  { label: 'Тип кузова', items: carBodyType },
  { label: 'Кількість місць', items: seatsCount },
  { label: 'Тип приводу', items: driveType },
  { label: "Об'єм двигуна", items: engineVolume },
  { label: 'Колір', items: color },
  { label: 'Лакове покриття', items: varnishCoating },
  { label: 'Технічний стан', items: technicalCondition },
  { label: 'Комфорт', items: comfort },
  { label: 'Мультимедіа', items: multimedia },
  { label: 'Безпека', items: security },
  { label: 'Розмитнена', items: сustomsСleared },
  { label: 'Авто пригнано з', items: theCarWasDrivenFrom },
]

export const createAdFields = [
  { label: 'Технічний стан', items: technicalCondition },
  { label: 'Комфорт', items: comfort },
  { label: 'Мультимедіа', items: multimedia },
  { label: 'Безпека', items: security },
]

export const adExamples = [
  {
    title: 'esse ut anim velit',
    price: 5000000,
    status: 'НЕАКТИВНЕ',
    category: 'Вантажні автомобілі',
    subcategory: 'Rover',
    carType: 'З пробігом',
    mileage: 5849,
    сustomsСleared: 'Ні',
    engineVolume: 7,
    theCarWasDrivenFrom: 'Молдова',
    model: 'Lorem',
    yearOfRelease: 2020,
    carBodyType: 'Ліфтбек',
    seatsCount: 4,
    color: 'Синій',
    gearbox: 'Варіатор',
    driveType: 'Повний',
    fuelType: 'Гібрид',
    varnishCoating: 'Незначні сліди експлуатації (дрібні подряпини, сколи)',
    technicalCondition: ['Не на ходу'],
    comfort: ['Мультируль', 'Кондиціонер', 'Підігрів дзеркал', 'Алькантара', "Пам'ять сидінь"],
    multimedia: ['Apple CarPay', 'Android Auto', 'Підсилювач'],
    security: ['Пневмопідвіска', 'Галогенні фари', 'ABD', 'LED фари', 'Центральний замок'],
    photos: [20, 18, 16, 19],
    user: 2,
    createdAt: 'Wed Jul 16 1980 11:11:09 GMT+0300 (Восточная Европа, стандартное время)',
  },
  {
    title: 'pariatur voluptate cillum mollit',
    price: 1000000,
    status: 'ОЧІКУЄ ПІДТВЕРДЖЕННЯ',
    category: 'Інший транспорт',
    subcategory: 'Hummer',
    carType: 'Новий',
    mileage: 4271,
    сustomsСleared: 'Так',
    engineVolume: 2,
    theCarWasDrivenFrom: 'Португалія',
    model: 'adipisicing esse ut',
    yearOfRelease: 2014,
    carBodyType: 'Седан',
    seatsCount: 4,
    color: 'Вишневий',
    gearbox: 'Автоматична',
    driveType: 'Передній',
    fuelType: 'Бензин',
    varnishCoating: 'Як нове, без видимих слідів експлуатації',
    technicalCondition: ['Після ДТП'],
    comfort: [
      'Алькантара',
      'Шкіряний салон',
      'Підсилювач керма',
      'Мультируль',
      'Ел. регулювання сидінь',
      'Кондиціонер',
      'Передня камера',
      'Передня камера',
      'Електропакет',
      'Клімат контроль',
    ],
    multimedia: ['Акустика', 'AUX', 'Apple CarPay', 'Сабвуфер'],
    security: ['LED фари'],
    photos: [19, 16, 17],
    user: 3,
    createdAt: 'Mon Jun 27 2016 09:05:04 GMT+0300 (Восточная Европа, летнее время)',
  },
  {
    title: 'laboris non veniam eu veniam consectetur nisi et',
    price: 1750000,
    status: 'НЕАКТИВНЕ',
    category: 'Легкові автомобілі',
    subcategory: 'Chevrolet',
    carType: 'Новий',
    mileage: 18467,
    сustomsСleared: 'Так',
    engineVolume: 7,
    theCarWasDrivenFrom: 'Італія',
    model: 'culpa non tempor',
    yearOfRelease: 2021,
    carBodyType: 'Купе',
    seatsCount: 5,
    color: 'Синій',
    gearbox: 'Автоматична',
    driveType: 'Передній',
    fuelType: 'Дизель',
    varnishCoating: 'Як нове, без видимих слідів експлуатації',
    technicalCondition: [
      'Гаражне зберігання',
      'Потребує кузовного ремонту',
      'Сервісна книжка',
      'Не бита',
      'На ходу, технічно справна',
    ],
    comfort: ['Електропакет', 'Підігрів дзеркал', 'Підігрів сидінь', 'Датчик дощу', 'Підсилювач керма'],
    multimedia: ['Акустика'],
    security: ['Замок на КПП', 'Замок на КПП', 'Лазерні фари'],
    photos: [18, 19, 15, 17, 20],
    user: 2,
    createdAt: 'Thu Mar 02 2000 08:05:45 GMT+0200 (Восточная Европа, стандартное время)',
  },
  {
    title: 'exercitation dolor ad qui',
    price: 2300000,
    status: 'АКТИВНЕ',
    category: 'Автобуси',
    subcategory: 'Chery',
    carType: 'З пробігом',
    mileage: 95978,
    сustomsСleared: 'Ні',
    engineVolume: 3,
    theCarWasDrivenFrom: 'Литва',
    model: 'tempor esse',
    yearOfRelease: 2012,
    carBodyType: 'Кабріолет',
    seatsCount: 6,
    color: 'Золотистий',
    gearbox: 'Автоматична',
    driveType: 'Передній',
    fuelType: 'Газ / бензин',
    varnishCoating: 'Професійно відремонтоварі сліди експлуатації',
    technicalCondition: ['Не пофарбована'],
    comfort: [
      'Електросклопідйомники',
      'Підігрів сидінь',
      'Камера заднього виду',
      'Панорамний дах',
      'Клімат контроль',
      'Панорамний дах',
    ],
    multimedia: ['CD', 'Apple CarPay', 'Apple CarPay'],
    security: ['ABD', 'ABD'],
    photos: [19, 19, 16, 19, 17],
    user: 3,
    createdAt: 'Thu Dec 31 1998 03:48:49 GMT+0200 (Восточная Европа, стандартное время)',
  },
  {
    title: 'ipsum dolor cillum irure eiusmod incididunt deserunt',
    price: 1200000,
    status: 'АКТИВНЕ',
    category: 'Мото',
    subcategory: 'Dodge',
    carType: 'Під пригон (авто не в Україні)',
    mileage: 5849,
    сustomsСleared: 'Так',
    engineVolume: 4,
    theCarWasDrivenFrom: 'Франція',
    model: 'anim duis quis occaecat',
    yearOfRelease: 2021,
    carBodyType: 'Інший',
    seatsCount: 2,
    color: 'Червоний',
    gearbox: 'Типтронік',
    driveType: 'Передній',
    fuelType: 'Інший',
    varnishCoating: 'Професійно відремонтоварі сліди експлуатації',
    technicalCondition: ['Потребує кузовного ремонту', 'Потребує ремонту ходової'],
    comfort: ["Пам'ять сидінь", 'Люк', 'Підігрів дзеркал', 'Датчик світла', 'Клімат контроль', 'Електропакет'],
    multimedia: ['Магнітола', 'AUX', 'Система навігації GPS', 'Bluetooth'],
    security: [
      'Броньований автомобіль',
      'Сигналізація',
      'Броньований автомобіль',
      'Лазерні фари',
      'Замок на КПП',
      'ABS',
      'Галогенні фари',
      'ESP',
      'Галогенні фари',
    ],
    photos: [18, 20, 20, 19, 19, 20],
    user: 4,
    createdAt: 'Wed Feb 18 1970 21:54:37 GMT+0300 (Восточная Европа, стандартное время)',
  },
  {
    title: 'quis deserunt eu commodo esse',
    price: 120000,
    status: 'АКТИВНЕ',
    category: 'Легкові автомобілі',
    subcategory: 'Jeep',
    carType: 'З пробігом',
    mileage: 95978,
    сustomsСleared: 'Ні',
    engineVolume: 2,
    theCarWasDrivenFrom: 'Латвія',
    model: 'reprehenderit incididunt est',
    yearOfRelease: 2020,
    carBodyType: 'Лімузин',
    seatsCount: 5,
    color: 'Бежевий',
    gearbox: 'Адаптивна',
    driveType: 'Повний',
    fuelType: 'Бензин',
    varnishCoating: "Не відремонтовані сліди експлуатації (подряпини, вм'ятини і т.д.)",
    technicalCondition: ['Не бита', 'Гаражне зберігання', 'Потребує кузовного ремонту'],
    comfort: [
      'Обігрів керма',
      'Шкіряний салон',
      'Підігрів дзеркал',
      'Алькантара',
      'Запуск кнопкою',
      'Мультируль',
      'Панорамний дах',
      'Шкіряний салон',
      'Люк',
    ],
    multimedia: ['Система навігації GPS', 'Підсилювач'],
    security: [
      'Подушка безпеки (Airbag)',
      'Пневмопідвіска',
      'ABS',
      'ESP',
      'Подушка безпеки (Airbag)',
      'Пневмопідвіска',
      'Іммобілайзер',
      'Подушка безпеки (Airbag)',
      'ABS',
    ],
    photos: [19, 15, 18, 15, 15],
    user: 5,
    createdAt: 'Fri May 30 1975 11:24:04 GMT+0300 (Восточная Европа, стандартное время)',
  },
  {
    title: 'incididunt dolor exercitation aliqua ut',
    price: 800000,
    status: 'ОЧІКУЄ ПІДТВЕРДЖЕННЯ',
    category: 'Легкові автомобілі',
    subcategory: 'Maybach',
    carType: 'Новий',
    mileage: 100,
    сustomsСleared: 'Так',
    engineVolume: 3,
    theCarWasDrivenFrom: 'Норвегія',
    model: 'incididunt',
    yearOfRelease: 2012,
    carBodyType: 'Універсал',
    seatsCount: '8 і більше',
    color: 'Чорний',
    gearbox: 'Механічна',
    driveType: 'Повний',
    fuelType: 'Бензин',
    varnishCoating: 'Потрібно відновлення (фарбування, заміна деталей, зварювання)',
    technicalCondition: ['Не бита', 'Перший власник', 'Не пофарбована', 'Не пофарбована'],
    comfort: [
      'Камера заднього виду',
      'Датчик дощу',
      'Мультируль',
      'Підігрів дзеркал',
      'Передня камера',
      'Круїз контроль',
    ],
    multimedia: ['Підсилювач', 'Акустика', 'Акустика', 'CD', 'Система навігації GPS', 'Сабвуфер', 'CD'],
    security: [
      'Пневмопідвіска',
      'ABS',
      'Пневмопідвіска',
      'Броньований автомобіль',
      'Пневмопідвіска',
      'Замок на КПП',
      'ABS',
      'Замок на КПП',
    ],
    photos: [16, 18, 20, 15, 17, 15],
    user: 6,
    createdAt: 'Wed Feb 14 1990 01:00:05 GMT+0300 (Восточная Европа, стандартное время)',
  },
  {
    title: 'culpa reprehenderit nostrud Lorem',
    price: 2300000,
    status: 'НЕАКТИВНЕ',
    category: 'Мото',
    subcategory: 'Dacia',
    carType: 'Під пригон (авто не в Україні)',
    mileage: 5849,
    сustomsСleared: 'Так',
    engineVolume: 3,
    theCarWasDrivenFrom: 'Португалія',
    model: 'ullamco consequat in',
    yearOfRelease: 2022,
    carBodyType: 'Ліфтбек',
    seatsCount: 4,
    color: 'Оливковий',
    gearbox: 'Варіатор',
    driveType: 'Повний',
    fuelType: 'Гібрид',
    varnishCoating: 'Як нове, без видимих слідів експлуатації',
    technicalCondition: ['Не пофарбована'],
    comfort: ['Кондиціонер', "Пам'ять сидінь", 'Передня камера', "Бортовий комп'ютер"],
    multimedia: ['Bluetooth', 'Bluetooth', 'Android Auto', 'Android Auto', 'Bluetooth', 'USB', 'Android Auto', 'AUX'],
    security: [
      'Броньований автомобіль',
      'ABD',
      'ESP',
      'ABD',
      'LED фари',
      'Центральний замок',
      'Галогенні фари',
      'Подушка безпеки (Airbag)',
      'ABD',
    ],
    photos: [17, 18, 20, 16, 17, 20],
    user: 7,
    createdAt: 'Wed Dec 17 2014 23:07:23 GMT+0200 (Восточная Европа, стандартное время)',
  },
  {
    title: 'mollit irure tempor labore',
    price: 3000000,
    status: 'АКТИВНЕ',
    category: 'Автобуси',
    subcategory: 'Peugeot',
    carType: 'З пробігом',
    mileage: 586,
    сustomsСleared: 'Так',
    engineVolume: 5,
    theCarWasDrivenFrom: 'Молдова',
    model: 'deserunt enim mollit',
    yearOfRelease: 2011,
    carBodyType: 'Інший',
    seatsCount: 6,
    color: 'Блакитний',
    gearbox: 'Адаптивна',
    driveType: 'Передній',
    fuelType: 'Газ / бензин',
    varnishCoating: 'Професійно відремонтоварі сліди експлуатації',
    technicalCondition: ['Перший власник', 'Після ДТП'],
    comfort: [
      'Запуск кнопкою',
      'Електропакет',
      'Запуск кнопкою',
      "Бортовий комп'ютер",
      'Електропакет',
      'Шкіряний салон',
    ],
    multimedia: ['Сабвуфер', 'Підсилювач'],
    security: ['Сервокермо', 'Сервокермо', 'Сервокермо', 'Сигналізація'],
    photos: [17, 20, 18, 16],
    user: 4,
    createdAt: 'Tue Aug 20 1996 00:50:14 GMT+0300 (Восточная Европа, летнее время)',
  },
  {
    title: 'eu dolore voluptate labore',
    price: 1500000,
    status: 'НЕАКТИВНЕ',
    category: 'Інший транспорт',
    subcategory: 'Chrysler',
    carType: 'Новий',
    mileage: 4271,
    сustomsСleared: 'Так',
    engineVolume: 7,
    theCarWasDrivenFrom: 'Португалія',
    model: 'eiusmod sunt fugiat sit',
    yearOfRelease: 2015,
    carBodyType: 'Ліфтбек',
    seatsCount: 4,
    color: 'Жовтий',
    gearbox: 'Типтронік',
    driveType: 'Задній',
    fuelType: 'Електро',
    varnishCoating: 'Професійно відремонтоварі сліди експлуатації',
    technicalCondition: ['Гаражне зберігання'],
    comfort: [
      'Мультируль',
      'Кондиціонер',
      'Кондиціонер',
      'Обігрів керма',
      'Кондиціонер',
      'Передня камера',
      'Підігрів дзеркал',
      'Мультируль',
      'Датчик світла',
    ],
    multimedia: [
      'Система навігації GPS',
      'USB',
      'USB',
      'Акустика',
      'Bluetooth',
      'Система навігації GPS',
      'Підсилювач',
      'Магнітола',
    ],
    security: ['Галогенні фари', 'Замок на КПП', 'Іммобілайзер'],
    photos: [15, 16, 19],
    user: 5,
    createdAt: 'Thu Oct 29 1992 13:47:03 GMT+0200 (Восточная Европа, стандартное время)',
  },
  {
    title: 'non Lorem ex quis irure',
    price: 800000,
    status: 'АКТИВНЕ',
    category: 'Інший транспорт',
    subcategory: 'Alfa Romeo',
    carType: 'З пробігом',
    mileage: 586,
    сustomsСleared: 'Так',
    engineVolume: 5,
    theCarWasDrivenFrom: 'США',
    model: 'pariatur quis',
    yearOfRelease: 2012,
    carBodyType: 'Купе',
    seatsCount: 6,
    color: 'Коричневий',
    gearbox: 'Адаптивна',
    driveType: 'Задній',
    fuelType: 'Газ / бензин',
    varnishCoating: 'Незначні сліди експлуатації (дрібні подряпини, сколи)',
    technicalCondition: ['Не на ходу', 'Перший власник', 'Перший власник', 'Гаражне зберігання'],
    comfort: [
      'Мультируль',
      'Кондиціонер',
      'Обігрів керма',
      'Панорамний дах',
      'Шкіряний салон',
      'Датчик світла',
      'Електропакет',
      'Запуск кнопкою',
    ],
    multimedia: [
      'Android Auto',
      'CD',
      'Android Auto',
      'Android Auto',
      'Магнітола',
      'AUX',
      'Система навігації GPS',
      'Система навігації GPS',
      'Акустика',
      'CD',
    ],
    security: ['Сигналізація', 'LED фари', 'ESP', 'Пневмопідвіска', 'Замок на КПП', 'ABS', 'ABD', 'ESP'],
    photos: [20, 18, 20, 19, 17, 18],
    user: 6,
    createdAt: 'Thu Jul 18 2019 04:04:22 GMT+0300 (Восточная Европа, летнее время)',
  },
  {
    title: 'incididunt ipsum voluptate culpa id',
    price: 100000,
    status: 'НЕАКТИВНЕ',
    category: 'Легкові автомобілі',
    subcategory: 'Land Rover',
    carType: 'З пробігом',
    mileage: 2834,
    сustomsСleared: 'Так',
    engineVolume: 2,
    theCarWasDrivenFrom: 'Іспанія',
    model: 'non',
    yearOfRelease: 2022,
    carBodyType: 'Седан',
    seatsCount: 2,
    color: 'Червоний',
    gearbox: 'Типтронік',
    driveType: 'Задній',
    fuelType: 'Дизель',
    varnishCoating: 'Потрібно відновлення (фарбування, заміна деталей, зварювання)',
    technicalCondition: ['Після ДТП', 'Сервісна книжка', 'Гаражне зберігання'],
    comfort: ["Бортовий комп'ютер", 'Підігрів дзеркал', 'Підсилювач керма'],
    multimedia: ['Сабвуфер', 'Apple CarPay', 'Сабвуфер', 'AUX', 'CD', 'Сабвуфер', 'Акустика'],
    security: ['ABS'],
    photos: [19, 15, 18, 15, 20, 16],
    user: 7,
    createdAt: 'Wed Sep 05 2012 15:44:33 GMT+0300 (Восточная Европа, летнее время)',
  },
  {
    title: 'tempor sint cupidatat minim',
    price: 1750000,
    status: 'ОЧІКУЄ ПІДТВЕРДЖЕННЯ',
    category: 'Вантажні автомобілі',
    subcategory: 'Kia',
    carType: 'Новий',
    mileage: 1893,
    сustomsСleared: 'Ні',
    engineVolume: 6,
    theCarWasDrivenFrom: 'Португалія',
    model: 'occaecat quis laborum',
    yearOfRelease: 2023,
    carBodyType: 'Кабріолет',
    seatsCount: 4,
    color: 'Сріблястий',
    gearbox: 'Механічна',
    driveType: 'Передній',
    fuelType: 'Газ / бензин',
    varnishCoating: 'Потрібно відновлення (фарбування, заміна деталей, зварювання)',
    technicalCondition: ['Не на ходу', 'Не на ходу', 'Після ДТП'],
    comfort: ['Запуск кнопкою', 'Передня камера', 'Передня камера'],
    multimedia: ['CD', 'USB', 'CD'],
    security: ['Галогенні фари', 'Сигналізація'],
    photos: [15],
    user: 6,
    createdAt: 'Wed Jan 20 1982 00:51:25 GMT+0300 (Восточная Европа, стандартное время)',
  },
  {
    title: 'do dolore eiusmod ex pariatur enim',
    price: 1700000,
    status: 'ОЧІКУЄ ПІДТВЕРДЖЕННЯ',
    category: 'Інший транспорт',
    subcategory: 'Geely',
    carType: 'Під пригон (авто не в Україні)',
    mileage: 48561,
    сustomsСleared: 'Ні',
    engineVolume: 5,
    theCarWasDrivenFrom: 'Португалія',
    model: 'amet excepteur',
    yearOfRelease: 2014,
    carBodyType: 'Універсал',
    seatsCount: '8 і більше',
    color: 'Бірюзовий',
    gearbox: 'Механічна',
    driveType: 'Повний',
    fuelType: 'Гібрид',
    varnishCoating: 'Потрібно відновлення (фарбування, заміна деталей, зварювання)',
    technicalCondition: ['Перший власник', 'Не на ходу', 'Потребує ремонту двигуна'],
    comfort: [
      'Круїз контроль',
      'Електросклопідйомники',
      'Датчик світла',
      "Пам'ять сидінь",
      'Передня камера',
      'Мультируль',
      'Електросклопідйомники',
    ],
    multimedia: [
      'Система навігації GPS',
      'Android Auto',
      'Bluetooth',
      'Підсилювач',
      'Сабвуфер',
      'Система навігації GPS',
      'USB',
    ],
    security: ['LED фари', 'ABD', 'LED фари', 'LED фари'],
    photos: [17, 16],
    user: 5,
    createdAt: 'Sun Feb 15 1998 09:12:54 GMT+0200 (Восточная Европа, стандартное время)',
  },
  {
    title: 'proident nostrud enim non enim mollit nisi',
    price: 5000000,
    status: 'ОЧІКУЄ ПІДТВЕРДЖЕННЯ',
    category: 'Вантажні автомобілі',
    subcategory: 'Renault',
    carType: 'З пробігом',
    mileage: 2834,
    сustomsСleared: 'Так',
    engineVolume: 7,
    theCarWasDrivenFrom: 'Швейцарія',
    model: 'laboris sunt fugiat nostrud',
    yearOfRelease: 2024,
    carBodyType: 'Інший',
    seatsCount: 4,
    color: 'Синій',
    gearbox: 'Адаптивна',
    driveType: 'Задній',
    fuelType: 'Інший',
    varnishCoating: 'Потрібно відновлення (фарбування, заміна деталей, зварювання)',
    technicalCondition: ['Не на ходу'],
    comfort: [
      'Мультируль',
      'Панорамний дах',
      'Клімат контроль',
      'Обігрів керма',
      'Запуск кнопкою',
      'Круїз контроль',
      'Омивач фар',
    ],
    multimedia: ['Магнітола'],
    security: [
      'ABD',
      'ABD',
      'ESP',
      'ESP',
      'Центральний замок',
      'Лазерні фари',
      'Броньований автомобіль',
      'Сервокермо',
      'ESP',
    ],
    photos: [19, 16, 18, 15],
    user: 4,
    createdAt: 'Sun Sep 19 1993 18:27:48 GMT+0300 (Восточная Европа, летнее время)',
  },
  {
    title: 'laborum aute aliquip occaecat culpa esse',
    price: 1200000,
    status: 'НЕАКТИВНЕ',
    category: 'Мото',
    subcategory: 'Citroen',
    carType: 'Новий',
    mileage: 3721,
    сustomsСleared: 'Так',
    engineVolume: 6,
    theCarWasDrivenFrom: 'Швейцарія',
    model: 'deserunt aliquip deserunt',
    yearOfRelease: 2012,
    carBodyType: 'Хетчбек',
    seatsCount: 2,
    color: 'Вишневий',
    gearbox: 'Варіатор',
    driveType: 'Задній',
    fuelType: 'Бензин',
    varnishCoating: 'Як нове, без видимих слідів експлуатації',
    technicalCondition: ['Потребує кузовного ремонту', 'Перший власник'],
    comfort: ['Підігрів дзеркал'],
    multimedia: ['Apple CarPay', 'Сабвуфер', 'Android Auto', 'Магнітола', 'CD'],
    security: ['Сервокермо', 'Замок на КПП', 'Пневмопідвіска', 'LED фари', 'ABS', 'LED фари', 'Іммобілайзер'],
    photos: [19],
    user: 7,
    createdAt: 'Sun Mar 24 1996 06:09:40 GMT+0200 (Восточная Европа, стандартное время)',
  },
  {
    title: 'officia commodo id magna occaecat',
    price: 150000,
    status: 'ОЧІКУЄ ПІДТВЕРДЖЕННЯ',
    category: 'Вантажні автомобілі',
    subcategory: 'Opel',
    carType: 'Під пригон (авто не в Україні)',
    mileage: 586,
    сustomsСleared: 'Ні',
    engineVolume: 7,
    theCarWasDrivenFrom: 'Іспанія',
    model: 'sint laboris velit consequat',
    yearOfRelease: 2011,
    carBodyType: 'Хетчбек',
    seatsCount: '8 і більше',
    color: 'Вишневий',
    gearbox: 'Адаптивна',
    driveType: 'Передній',
    fuelType: 'Газ / бензин',
    varnishCoating: "Не відремонтовані сліди експлуатації (подряпини, вм'ятини і т.д.)",
    technicalCondition: ['Не на ходу', 'Гаражне зберігання', 'На ходу, технічно справна'],
    comfort: ['Електросклопідйомники', 'Обігрів керма', 'Підігрів дзеркал'],
    multimedia: [
      'Магнітола',
      'CD',
      'Android Auto',
      'Магнітола',
      'Підсилювач',
      'Система навігації GPS',
      'Сабвуфер',
      'Підсилювач',
      'Підсилювач',
    ],
    security: ['ABS', 'Сигналізація', 'ABD', 'ABS', 'Центральний замок'],
    photos: [18],
    user: 6,
    createdAt: 'Mon Nov 05 1984 21:54:02 GMT+0300 (Восточная Европа, стандартное время)',
  },
  {
    title: 'cupidatat ipsum fugiat non voluptate ex minim',
    price: 300000,
    status: 'ОЧІКУЄ ПІДТВЕРДЖЕННЯ',
    category: 'Автобуси',
    subcategory: 'Opel',
    carType: 'Новий',
    mileage: 95978,
    сustomsСleared: 'Так',
    engineVolume: 5,
    theCarWasDrivenFrom: 'Бельгія',
    model: 'amet velit',
    yearOfRelease: 2015,
    carBodyType: 'Інший',
    seatsCount: '8 і більше',
    color: 'Рожевий',
    gearbox: 'Механічна',
    driveType: 'Повний',
    fuelType: 'Газ / бензин',
    varnishCoating: 'Потрібно відновлення (фарбування, заміна деталей, зварювання)',
    technicalCondition: [
      'Не на ходу',
      'Гаражне зберігання',
      'Потребує кузовного ремонту',
      'Потребує ремонту ходової',
      'Не бита',
    ],
    comfort: [
      'Круїз контроль',
      'Датчик дощу',
      'Круїз контроль',
      'Люк',
      'Парктроник',
      'Датчик світла',
      'Тонування скла',
    ],
    multimedia: ['Сабвуфер', 'Apple CarPay', 'Акустика', 'Bluetooth'],
    security: [
      'Галогенні фари',
      'Сигналізація',
      'Пневмопідвіска',
      'Замок на КПП',
      'Центральний замок',
      'Броньований автомобіль',
    ],
    photos: [16, 19],
    user: 5,
    createdAt: 'Wed Sep 07 1983 01:42:21 GMT+0400 (Восточная Европа, летнее время)',
  },
  {
    title: 'sint veniam dolore cillum adipisicing',
    price: 120000,
    status: 'АКТИВНЕ',
    category: 'Вантажні автомобілі',
    subcategory: 'Nissan',
    carType: 'Новий',
    mileage: 3721,
    сustomsСleared: 'Ні',
    engineVolume: 4,
    theCarWasDrivenFrom: 'Португалія',
    model: 'sit elit aute',
    yearOfRelease: 2019,
    carBodyType: 'Ліфтбек',
    seatsCount: 5,
    color: 'Інший',
    gearbox: 'Механічна',
    driveType: 'Передній',
    fuelType: 'Дизель',
    varnishCoating: 'Потрібно відновлення (фарбування, заміна деталей, зварювання)',
    technicalCondition: ['Потребує ремонту ходової', 'Потребує ремонту ходової'],
    comfort: ['Круїз контроль', 'Шкіряний салон', 'Кондиціонер'],
    multimedia: ['AUX', 'Підсилювач', 'AUX', 'Apple CarPay'],
    security: ['ABD', 'Пневмопідвіска', 'Подушка безпеки (Airbag)'],
    photos: [15, 16, 17, 16, 17, 15],
    user: 4,
    createdAt: 'Fri Jul 26 1985 07:32:37 GMT+0400 (Восточная Европа, летнее время)',
  },
]

/* 
https://json-generator.com/


[
  '{{repeat(4, 10)}}',
  {
    id: '{{objectId()}}',
    title: '{{lorem([random(4, 5, 6, 7, 8)], "words")}}',
    price: '{{random(100000, 120000, 150000, 200000, 300000, 500000, 700000, 800000,1000000,1200000,1500000,1650000,1700000,1750000,2000000,2300000,3000000,5000000)}}',
    status: '{{random("ОЧІКУЄ ПІДТВЕРДЖЕННЯ","АКТИВНЕ","НЕАКТИВНЕ")}}',
    category: '{{random("Легкові автомобілі", "Вантажні автомобілі", "Автобуси", "Мото", "Інший транспорт")}}',
    subcategory: '{{random("Acura", "Alfa Romeo", "Aston Martin", "Audi", "Bentley", "BMW", "Buick", "Cadillac", "Chana", "Chery", "Chevrolet", "Chrysler", "Citroen", "Dacia", "Daewoo", "Dodge", "Ferrari", "Fiat", "Ford", "Geely", "Honda", "Hummer", "Huyndai", "Infinity", "Jaguar", "Jeep", "Kia", "Lamborghini", "Land Rover", "Lexus", "Lifan", "Lincoln", "Maserati", "Maybach", "Mazda", "McLaren", "Mercedes-Menz", "Mitsubishi", "Nissan", "Opel", "Peugeot", "Porsche", "Renault", "Rolls-Royse", "Rover", "Skoda", "Subaru", "Suzuki", "Tesla", "Toyota", "Volkswagen", "Volvo", "Інші")}}',
    carType: '{{random("З пробігом", "Новий", "Під пригон (авто не в Україні)")}}',
    mileage: '{{random("100", "2946", "5849", "95978", "48561", "4271", "3721", "586", "47328", "18467", "48510", "1893", "2834")}}',
    сustomsСleared: '{{random("Так", "Ні")}}',
    engineVolume: '{{random(1, 2, 3, 4, 5, 6, 7)}}',
    theCarWasDrivenFrom: '{{random("США", "Німеччина", "Литва", "Грузія", "Корея", "Польша", "Швейцарія", "Норвегія", "Франція", "Молдова", "Іспанія", "Італія", "Португалія", "Нідерланди" , "Бельгія" , "Латвія" , "Інша країна")}}',
    model: '{{lorem([random(1, 2, 3, 4)], "words")}}',
    yearOfRelease: '{{random("2012", "2015", "2016", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2010", "2011", "2014")}}',
    carBodyType: '{{random("Кабріолет", "Пікап", "Купе", "Універсал", "Хетчбек", "Мінівен", "Позашляховик / Кроссовер", "Седан", "Ліфтбек", "Лімузин", "Інший")}}',
    seatsCount: '{{random("2", "3", "4", "5", "6", "8 і більше")}}',
    color: '{{random("Білий", "Чорний", "Синій", "Сірий", "Сріблястий", "Червоний", "Зелений", "Бежевий", "Бірюзовий", "Бронзовий", "Вишневий", "Блакитний", "Жовтий", "Золотистий", "Коричневий", "Матовий", "Оливковий", "Рожевий", "Фіолетовий", "Інший")}}',
    gearbox: '{{random("Механічна", "Автоматична", "Варіатор", "Адаптивна", "Типтронік")}}',
    driveType: '{{random("Повний", "Передній", "Задній")}}',
    fuelType: '{{random("Бензин", "Дизель", "Газ / бензин", "Електро", "Гібрид", "Інший")}}',
    varnishCoating: '{{random("Як нове, без видимих слідів експлуатації", "Професійно відремонтоварі сліди експлуатації", "Незначні сліди експлуатації (дрібні подряпини, сколи)", "Не відремонтовані сліди експлуатації (подряпини, вм\'ятини і т.д.)", "Потрібно відновлення (фарбування, заміна деталей, зварювання)")}}',
    technicalCondition: [
      '{{repeat(1, 5)}}',
      '{{random("На ходу, технічно справна", "Не бита", "Не пофарбована", "Гаражне зберігання", "Перший власник", "Сервісна книжка", "Потребує кузовного ремонту", "Потребує ремонту ходової", "Потребує ремонту двигуна", "Після ДТП", "Не на ходу")}}'
    ],
    comfort: [
      '{{repeat(1, 10)}}',
      '{{random("Електропакет", "Електросклопідйомники", "Кондиціонер", "Парктроник", "Бортовий комп\'ютер", "Датчик світла", "Запуск кнопкою", "Клімат контроль", "Шкіряний салон", "Круїз контроль", "Люк", "Панорамний дах", "Ел. регулювання сидінь", "Камера заднього виду", "Передня камера", "Мультируль", "Омивач фар", "Підігрів дзеркал", "Обігрів керма", "Підсилювач керма", "Підігрів сидінь", "Тонування скла", "Пам\'ять сидінь", "Датчик дощу", "Алькантара")}}'
    ],
    multimedia: [
      '{{repeat(1, 10)}}',
      '{{random("CD", "AUX", "Bluetooth", "USB", "Акустика", "Магнітола", "Підсилювач", "Сабвуфер", "Система навігації GPS", "Apple CarPay", "Android Auto")}}'
    ],
    security: [
      '{{repeat(1, 10)}}',
      '{{random("ABD", "ABS", "ESP", "Броньований автомобіль", "Галогенні фари", "Замок на КПП", "Іммобілайзер", "Пневмопідвіска", "Подушка безпеки (Airbag)", "Сервокермо", "Сигналізація", "Центральний замок", "LED фари", "Лазерні фари")}}'
    ],
    photos: [
      '{{repeat(1, 6)}}',
      '{{random(15, 16, 17, 18, 19, 20)}}'
    ],
    user: user: '{{random(2, 3, 4, 5, 6, 7)}}',,
    createdAt: '{{date()}}'
  }
]
*/
