import { IFilter } from '@/redux/filter/FilterTypes'
import { IFilterCheckboxItem } from '@/types/catalog'

// Категорія
export const category = [
  { checked: false, id: '1', title: 'Легкові автомобілі', event: '' },
  { checked: false, id: '2', title: 'Вантажні автомобілі', event: '' },
  { checked: false, id: '3', title: 'Автобуси', event: '' },
  { checked: false, id: '4', title: 'Мото', event: '' },
  { checked: false, id: '5', title: 'Інший транспорт', event: '' },
]

// Виробник
export const subcategory = [
  { checked: false, id: '1', title: 'Acura', event: '' },
  { checked: false, id: '2', title: 'Alfa Romeo', event: '' },
  { checked: false, id: '3', title: 'Aston Martin', event: '' },
  { checked: false, id: '4', title: 'Audi', event: '' },
  { checked: false, id: '5', title: 'Bentley', event: '' },
  { checked: false, id: '6', title: 'BMW', event: '' },
  { checked: false, id: '7', title: 'Buick', event: '' },
  { checked: false, id: '8', title: 'Cadillac', event: '' },
  { checked: false, id: '9', title: 'Chana', event: '' },
  { checked: false, id: '10', title: 'Chery', event: '' },
  { checked: false, id: '11', title: 'Chevrolet', event: '' },
  { checked: false, id: '12', title: 'Chrysler', event: '' },
  { checked: false, id: '13', title: 'Citroen', event: '' },
  { checked: false, id: '14', title: 'Dacia', event: '' },
  { checked: false, id: '15', title: 'Daewoo', event: '' },
  { checked: false, id: '16', title: 'Dodge', event: '' },
  { checked: false, id: '17', title: 'Ferrari', event: '' },
  { checked: false, id: '18', title: 'Fiat', event: '' },
  { checked: false, id: '19', title: 'Ford', event: '' },
  { checked: false, id: '20', title: 'Geely', event: '' },
  { checked: false, id: '21', title: 'Honda', event: '' },
  { checked: false, id: '22', title: 'Hummer', event: '' },
  { checked: false, id: '23', title: 'Huyndai', event: '' },
  { checked: false, id: '24', title: 'Infinity', event: '' },
  { checked: false, id: '25', title: 'Jaguar', event: '' },
  { checked: false, id: '26', title: 'Jeep', event: '' },
  { checked: false, id: '27', title: 'Kia', event: '' },
  { checked: false, id: '28', title: 'Lamborghini', event: '' },
  { checked: false, id: '29', title: 'Land Rover', event: '' },
  { checked: false, id: '30', title: 'Lexus', event: '' },
  { checked: false, id: '31', title: 'Lifan', event: '' },
  { checked: false, id: '32', title: 'Lincoln', event: '' },
  { checked: false, id: '33', title: 'Maserati', event: '' },
  { checked: false, id: '34', title: 'Maybach', event: '' },
  { checked: false, id: '35', title: 'Mazda', event: '' },
  { checked: false, id: '36', title: 'McLaren', event: '' },
  { checked: false, id: '37', title: 'Mercedes-Menz', event: '' },
  { checked: false, id: '38', title: 'Mitsubishi', event: '' },
  { checked: false, id: '39', title: 'Nissan', event: '' },
  { checked: false, id: '40', title: 'Opel', event: '' },
  { checked: false, id: '41', title: 'Peugeot', event: '' },
  { checked: false, id: '42', title: 'Porsche', event: '' },
  { checked: false, id: '43', title: 'Renault', event: '' },
  { checked: false, id: '44', title: 'Rolls-Royse', event: '' },
  { checked: false, id: '45', title: 'Rover', event: '' },
  { checked: false, id: '46', title: 'Skoda', event: '' },
  { checked: false, id: '47', title: 'Subaru', event: '' },
  { checked: false, id: '48', title: 'Suzuki', event: '' },
  { checked: false, id: '49', title: 'Tesla', event: '' },
  { checked: false, id: '50', title: 'Toyota', event: '' },
  { checked: false, id: '51', title: 'Volkswagen', event: '' },
  { checked: false, id: '52', title: 'Volvo', event: '' },
  { checked: false, id: '53', title: 'Інші', event: '' },
]

// Тип автомобіля
export const carType = [
  { checked: false, id: '1', title: 'З пробігом', event: '' },
  { checked: false, id: '2', title: 'Новий', event: '' },
  { checked: false, id: '3', title: 'Під пригон (авто не в Україні)', event: '' },
]

// Коробка передач
export const gearbox = [
  { checked: false, id: '1', title: 'Механічна', event: '' },
  { checked: false, id: '2', title: 'Автоматична', event: '' },
  { checked: false, id: '3', title: 'Варіатор', event: '' },
  { checked: false, id: '4', title: 'Адаптивна', event: '' },
  { checked: false, id: '5', title: 'Типтронік', event: '' },
]

// Тип палива
export const fuelType = [
  { checked: false, id: '1', title: 'Бензин', event: '' },
  { checked: false, id: '2', title: 'Дизель', event: '' },
  { checked: false, id: '3', title: 'Газ / бензин', event: '' },
  { checked: false, id: '4', title: 'Електро', event: '' },
  { checked: false, id: '5', title: 'Гібрид', event: '' },
  { checked: false, id: '6', title: 'Інший', event: '' },
]

// Тип кузова
export const carBodyType = [
  { checked: false, id: '1', title: 'Кабріолет', event: '' },
  { checked: false, id: '2', title: 'Пікап', event: '' },
  { checked: false, id: '3', title: 'Купе', event: '' },
  { checked: false, id: '4', title: 'Універсал', event: '' },
  { checked: false, id: '5', title: 'Хетчбек', event: '' },
  { checked: false, id: '6', title: 'Мінівен', event: '' },
  { checked: false, id: '7', title: 'Позашляховик / Кроссовер', event: '' },
  { checked: false, id: '8', title: 'Седан', event: '' },
  { checked: false, id: '9', title: 'Ліфтбек', event: '' },
  { checked: false, id: '10', title: 'Лімузин', event: '' },
  { checked: false, id: '11', title: 'Інший', event: '' },
]

// Кількість місць
export const seatsCount = [
  { checked: false, id: '1', title: '2', event: '' },
  { checked: false, id: '2', title: '3', event: '' },
  { checked: false, id: '3', title: '4', event: '' },
  { checked: false, id: '4', title: '5', event: '' },
  { checked: false, id: '5', title: '6', event: '' },
  { checked: false, id: '6', title: '7', event: '' },
  { checked: false, id: '7', title: '8 і більше', event: '' },
]

// Тип приводу
export const driveType = [
  { checked: false, id: '1', title: 'Повний', event: '' },
  { checked: false, id: '2', title: 'Передній', event: '' },
  { checked: false, id: '3', title: 'Задній', event: '' },
]

// Об'єм двигуна
export const engineVolume = [
  { checked: false, id: '1', title: '1 л.', event: '' },
  { checked: false, id: '2', title: '2 л.', event: '' },
  { checked: false, id: '3', title: '3 л.', event: '' },
  { checked: false, id: '4', title: '5 л.', event: '' },
  { checked: false, id: '5', title: '7 л.', event: '' },
]

// Колір
export const color = [
  { checked: false, id: '1', title: 'Білий', event: '' },
  { checked: false, id: '2', title: 'Чорний', event: '' },
  { checked: false, id: '3', title: 'Синій', event: '' },
  { checked: false, id: '4', title: 'Сірий', event: '' },
  { checked: false, id: '5', title: 'Сріблястий', event: '' },
  { checked: false, id: '6', title: 'Червоний', event: '' },
  { checked: false, id: '7', title: 'Зелений', event: '' },
  { checked: false, id: '8', title: 'Бежевий', event: '' },
  { checked: false, id: '9', title: 'Бірюзовий', event: '' },
  { checked: false, id: '10', title: 'Бронзовий', event: '' },
  { checked: false, id: '11', title: 'Вишневий', event: '' },
  { checked: false, id: '12', title: 'Блакитний', event: '' },
  { checked: false, id: '13', title: 'Жовтий', event: '' },
  { checked: false, id: '14', title: 'Золотистий', event: '' },
  { checked: false, id: '15', title: 'Коричневий', event: '' },
  { checked: false, id: '16', title: 'Матовий', event: '' },
  { checked: false, id: '17', title: 'Оливковий', event: '' },
  { checked: false, id: '18', title: 'Рожевий', event: '' },
  { checked: false, id: '19', title: 'Фіолетовий', event: '' },
  { checked: false, id: '20', title: 'Інший', event: '' },
] as unknown as IFilterCheckboxItem[]

// Лакофарбове покриття
export const varnishCoating = [
  { checked: false, id: '1', title: 'Як нове, без видимих слідів експлуатації', event: '' },
  { checked: false, id: '2', title: 'Професійно відремонтоварі сліди експлуатації', event: '' },
  { checked: false, id: '3', title: 'Незначні сліди експлуатації (дрібні подряпини, сколи)', event: '' },
  { checked: false, id: '4', title: "Не відремонтовані сліди експлуатації (подряпини, вм'ятини і т.д.)", event: '' },
  { checked: false, id: '5', title: 'Потрібно відновлення (фарбування, заміна деталей, зварювання)', event: '' },
] as unknown as IFilterCheckboxItem[]

// Технічний стан
export const technicalCondition = [
  { checked: false, id: '1', title: 'На ходу, технічно справна', event: '' },
  { checked: false, id: '2', title: 'Не бита', event: '' },
  { checked: false, id: '3', title: 'Не пофарбована', event: '' },
  { checked: false, id: '4', title: 'Гаражне зберігання', event: '' },
  { checked: false, id: '5', title: 'Перший власник', event: '' },
  { checked: false, id: '6', title: 'Сервісна книжка', event: '' },
  { checked: false, id: '7', title: 'Потребує кузовного ремонту', event: '' },
  { checked: false, id: '8', title: 'Потребує ремонту ходової', event: '' },
  { checked: false, id: '9', title: 'Потребує ремонту двигуна', event: '' },
  { checked: false, id: '10', title: 'Після ДТП', event: '' },
  { checked: false, id: '11', title: 'Не на ходу', event: '' },
] as unknown as IFilterCheckboxItem[]

// Комфорт
export const comfort = [
  { checked: false, id: '1', title: 'Електропакет', event: '' },
  { checked: false, id: '2', title: 'Електросклопідйомники', event: '' },
  { checked: false, id: '3', title: 'Кондиціонер', event: '' },
  { checked: false, id: '4', title: 'Парктроник', event: '' },
  { checked: false, id: '5', title: "Бортовий комп'ютер", event: '' },
  { checked: false, id: '6', title: 'Датчик світла', event: '' },
  { checked: false, id: '7', title: 'Запуск кнопкою', event: '' },
  { checked: false, id: '8', title: 'Клімат контроль', event: '' },
  { checked: false, id: '9', title: 'Шкіряний салон', event: '' },
  { checked: false, id: '10', title: 'Круїз контроль', event: '' },
  { checked: false, id: '11', title: 'Люк', event: '' },
  { checked: false, id: '12', title: 'Панорамний дах', event: '' },
  { checked: false, id: '13', title: 'Ел. регулювання сидінь', event: '' },
  { checked: false, id: '14', title: 'Камера заднього виду', event: '' },
  { checked: false, id: '15', title: 'Передня камера', event: '' },
  { checked: false, id: '16', title: 'Мультируль', event: '' },
  { checked: false, id: '17', title: 'Омивач фар', event: '' },
  { checked: false, id: '18', title: 'Підігрів дзеркал', event: '' },
  { checked: false, id: '19', title: 'Обігрів керма', event: '' },
  { checked: false, id: '20', title: 'Підсилювач керма', event: '' },
  { checked: false, id: '21', title: 'Підігрів сидінь', event: '' },
  { checked: false, id: '22', title: 'Тонування скла', event: '' },
  { checked: false, id: '23', title: "Пам'ять сидінь", event: '' },
  { checked: false, id: '24', title: 'Датчик дощу', event: '' },
  { checked: false, id: '25', title: 'Алькантара', event: '' },
] as unknown as IFilterCheckboxItem[]

// Мультимедіа (
export const multimedia = [
  { checked: false, id: '1', title: 'CD', event: '' },
  { checked: false, id: '2', title: 'AUX', event: '' },
  { checked: false, id: '3', title: 'Bluetooth', event: '' },
  { checked: false, id: '4', title: 'USB', event: '' },
  { checked: false, id: '5', title: 'Акустика', event: '' },
  { checked: false, id: '6', title: 'Магнітола', event: '' },
  { checked: false, id: '7', title: 'Підсилювач', event: '' },
  { checked: false, id: '8', title: 'Сабвуфер', event: '' },
  { checked: false, id: '9', title: 'Система навігації GPS', event: '' },
  { checked: false, id: '10', title: 'Apple CarPay', event: '' },
  { checked: false, id: '11', title: 'Android Auto', event: '' },
]

// Безпека
export const security = [
  { checked: false, id: '1', title: 'ABD', event: '' },
  { checked: false, id: '2', title: 'ABS', event: '' },
  { checked: false, id: '3', title: 'ESP', event: '' },
  { checked: false, id: '4', title: 'Броньований автомобіль', event: '' },
  { checked: false, id: '5', title: 'Галогенні фари', event: '' },
  { checked: false, id: '6', title: 'Замок на КПП', event: '' },
  { checked: false, id: '7', title: 'Іммобілайзер', event: '' },
  { checked: false, id: '8', title: 'Пневмопідвіска', event: '' },
  { checked: false, id: '9', title: 'Подушка безпеки (Airbag)', event: '' },
  { checked: false, id: '10', title: 'Сервокермо', event: '' },
  { checked: false, id: '11', title: 'Сигналізація', event: '' },
  { checked: false, id: '12', title: 'Центральний замок', event: '' },
  { checked: false, id: '13', title: 'LED фари', event: '' },
  { checked: false, id: '14', title: 'Лазерні фари', event: '' },
  { checked: false, id: '15', title: 'Кснон', event: '' },
  { checked: false, id: '16', title: 'Денні ходові вогні', event: '' },
  { checked: false, id: '17', title: 'GPS трекер', event: '' },
  { checked: false, id: '18', title: 'Безключовий доступ', event: '' },
]

// Розмитнена
export const сustomsСleared = [
  { checked: false, id: '1', title: 'Так', event: '' },
  { checked: false, id: '2', title: 'Ні', event: '' },
  { checked: false, id: '3', title: 'Розмитнення "під ключ"', event: '' },
]

// Авто пригнано з
export const theCarWasDrivenFrom = [
  { checked: false, id: '1', title: 'США', event: '' },
  { checked: false, id: '2', title: 'Німеччина', event: '' },
  { checked: false, id: '3', title: 'Литва', event: '' },
  { checked: false, id: '4', title: 'Грузія', event: '' },
  { checked: false, id: '5', title: 'Корея', event: '' },
  { checked: false, id: '6', title: 'Польша', event: '' },
  { checked: false, id: '7', title: 'Швейцарія', event: '' },
  { checked: false, id: '8', title: 'Норвегія', event: '' },
  { checked: false, id: '9', title: 'Франція', event: '' },
  { checked: false, id: '10', title: 'Молдова', event: '' },
  { checked: false, id: '11', title: 'Іспанія', event: '' },
  { checked: false, id: '12', title: 'Італія', event: '' },
  { checked: false, id: '13', title: 'Португалія', event: '' },
  { checked: false, id: '14', title: 'Нідерланди', event: '' },
  { checked: false, id: '15', title: 'Бельгія', event: '' },
  { checked: false, id: '16', title: 'Латвія', event: '' },
  { checked: false, id: '17', title: 'Інша країна', event: '' },
]

export const filters = [
  { label: 'Категорія', items: category },
  { label: 'Виробник', items: subcategory },
  { label: 'Тип автомобіля', items: carType },
  { label: 'Коробка передач', items: gearbox },
  { label: 'Тип палива', items: fuelType },
  { label: 'Тип кузова', items: carBodyType },
  { label: 'Кількість місць', items: seatsCount },
  { label: 'Тип приводу', items: driveType },
  { label: "Об'єм двигуна", items: engineVolume },
  { label: 'Колір', items: color },
  { label: 'Лакофарбове покриття', items: varnishCoating },
  { label: 'Технічний стан', items: technicalCondition },
  { label: 'Комфорт', items: comfort },
  { label: 'Мультимедіа', items: multimedia },
  { label: 'Безпека', items: security },
  { label: 'Розмитнена', items: сustomsСleared },
  { label: 'Авто пригнано з', items: theCarWasDrivenFrom },
] as IFilter[]

export const createAdFields = [
  { label: 'Технічний стан', items: technicalCondition },
  { label: 'Комфорт', items: comfort },
  { label: 'Мультимедіа', items: multimedia },
  { label: 'Безпека', items: security },
]

export const adExamples = [
  {
    title: 'cillum reprehenderit ex velit irure veniam qui',
    price: 1750000,
    status: 'АКТИВНЕ',
    category: 'Інший транспорт',
    subcategory: 'Chery',
    carType: 'Новий',
    mileage: 18467,
    сustomsСleared: 'Ні',
    engineVolume: 2,
    theCarWasDrivenFrom: 'Литва',
    model: 'est',
    yearOfRelease: 2016,
    carBodyType: 'Ліфтбек',
    seatsCount: 4,
    color: 'Вишневий',
    gearbox: 'Механічна',
    driveType: 'Повний',
    fuelType: 'Інший',
    varnishCoating: 'Професійно відремонтоварі сліди експлуатації',
    technicalCondition: ['Перший власник', 'Перший власник', 'Не пофарбована', 'Сервісна книжка', 'Не на ходу'],
    comfort: ['Кондиціонер', 'Парктроник', "Бортовий комп'ютер"],
    multimedia: [
      'Bluetooth',
      'Apple CarPay',
      'Android Auto',
      'USB',
      'Система навігації GPS',
      'Підсилювач',
      'AUX',
      'AUX',
      'Система навігації GPS',
    ],
    security: ['ESP', 'ABD', 'Сервокермо', 'ABD', 'Пневмопідвіска', 'Сервокермо'],
    photos: [36, 34],
    user: 4,
    createdAt: 'Mon Jun 18 2012 05:52:30 GMT+0300 (за східноєвропейським літнім часом)',
  },
  {
    title: 'ad sit qui ea nulla',
    price: 700000,
    status: 'АКТИВНЕ',
    category: 'Вантажні автомобілі',
    subcategory: 'Maserati',
    carType: 'Під пригон (авто не в Україні)',
    mileage: 48561,
    сustomsСleared: 'Ні',
    engineVolume: 3,
    theCarWasDrivenFrom: 'Італія',
    model: 'do',
    yearOfRelease: 2020,
    carBodyType: 'Лімузин',
    seatsCount: 5,
    color: 'Блакитний',
    gearbox: 'Типтронік',
    driveType: 'Передній',
    fuelType: 'Гібрид',
    varnishCoating: 'Незначні сліди експлуатації (дрібні подряпини, сколи)',
    technicalCondition: ['Потребує кузовного ремонту', 'Перший власник', 'Не пофарбована', 'Не пофарбована'],
    comfort: ['Підігрів дзеркал', 'Підсилювач керма', 'Запуск кнопкою', 'Передня камера', 'Люк'],
    multimedia: ['CD', 'Акустика', 'Акустика'],
    security: ['ABS', 'Сигналізація', 'LED фари', 'Іммобілайзер'],
    photos: [34, 36, 36, 33, 32],
    user: 3,
    createdAt: 'Tue Oct 31 2023 18:36:36 GMT+0200 (за східноєвропейським стандартним часом)',
  },
  {
    title: 'incididunt dolor consequat excepteur deserunt nulla ex',
    price: 2000000,
    status: 'НЕАКТИВНЕ',
    category: 'Автобуси',
    subcategory: 'Ferrari',
    carType: 'З пробігом',
    mileage: 48510,
    сustomsСleared: 'Ні',
    engineVolume: 1,
    theCarWasDrivenFrom: 'Бельгія',
    model: 'do nulla',
    yearOfRelease: 2014,
    carBodyType: 'Мінівен',
    seatsCount: 6,
    color: 'Бежевий',
    gearbox: 'Автоматична',
    driveType: 'Повний',
    fuelType: 'Електро',
    varnishCoating: 'Незначні сліди експлуатації (дрібні подряпини, сколи)',
    technicalCondition: ['Не бита', 'На ходу, технічно справна', 'Гаражне зберігання', 'Не бита', 'Не на ходу'],
    comfort: ['Датчик дощу', 'Круїз контроль', 'Електросклопідйомники'],
    multimedia: ['Apple CarPay', 'CD', 'AUX', 'USB'],
    security: ['Центральний замок', 'Галогенні фари'],
    photos: [35, 37, 36, 35],
    user: 3,
    createdAt: 'Wed Oct 14 1970 13:03:04 GMT+0300 (за східноєвропейським стандартним часом)',
  },
  {
    title: 'enim velit aliquip duis',
    price: 150000,
    status: 'НЕАКТИВНЕ',
    category: 'Інший транспорт',
    subcategory: 'Nissan',
    carType: 'Під пригон (авто не в Україні)',
    mileage: 2946,
    сustomsСleared: 'Ні',
    engineVolume: 2,
    theCarWasDrivenFrom: 'Швейцарія',
    model: 'velit magna in exercitation',
    yearOfRelease: 2018,
    carBodyType: 'Пікап',
    seatsCount: 4,
    color: 'Рожевий',
    gearbox: 'Варіатор',
    driveType: 'Повний',
    fuelType: 'Газ / бензин',
    varnishCoating: 'Професійно відремонтоварі сліди експлуатації',
    technicalCondition: ['Не пофарбована', 'На ходу, технічно справна', 'Потребує ремонту двигуна', 'Перший власник'],
    comfort: [
      'Парктроник',
      'Передня камера',
      'Парктроник',
      'Люк',
      'Люк',
      'Шкіряний салон',
      'Обігрів керма',
      'Омивач фар',
      'Люк',
      'Тонування скла',
    ],
    multimedia: ['AUX', 'USB', 'Android Auto', 'Bluetooth'],
    security: [
      'ABS',
      'Пневмопідвіска',
      'Броньований автомобіль',
      'Сигналізація',
      'Галогенні фари',
      'Іммобілайзер',
      'Іммобілайзер',
      'Пневмопідвіска',
    ],
    photos: [33],
    user: 6,
    createdAt: 'Sun Jan 20 1974 14:43:10 GMT+0300 (за східноєвропейським стандартним часом)',
  },
  {
    title: 'magna quis excepteur esse',
    price: 120000,
    status: 'АКТИВНЕ',
    category: 'Автобуси',
    subcategory: 'Lincoln',
    carType: 'З пробігом',
    mileage: 47328,
    сustomsСleared: 'Так',
    engineVolume: 6,
    theCarWasDrivenFrom: 'США',
    model: 'id proident esse',
    yearOfRelease: 2022,
    carBodyType: 'Позашляховик / Кроссовер',
    seatsCount: 4,
    color: 'Бежевий',
    gearbox: 'Автоматична',
    driveType: 'Передній',
    fuelType: 'Дизель',
    varnishCoating: 'Професійно відремонтоварі сліди експлуатації',
    technicalCondition: ['Потребує кузовного ремонту', 'Не на ходу', 'Не пофарбована'],
    comfort: ['Підігрів дзеркал', "Пам'ять сидінь", 'Парктроник'],
    multimedia: ['Акустика', 'CD', 'Apple CarPay', 'Система навігації GPS', 'Акустика', 'AUX'],
    security: ['Сервокермо', 'Іммобілайзер', 'Галогенні фари'],
    photos: [32, 33, 34],
    user: 3,
    createdAt: 'Sat Sep 12 1981 23:22:00 GMT+0400 (за східноєвропейським літнім часом)',
  },
  {
    title: 'mollit excepteur aute anim ea labore',
    price: 1700000,
    status: 'АКТИВНЕ',
    category: 'Легкові автомобілі',
    subcategory: 'Huyndai',
    carType: 'З пробігом',
    mileage: 100,
    сustomsСleared: 'Так',
    engineVolume: 3,
    theCarWasDrivenFrom: 'Швейцарія',
    model: 'ex do',
    yearOfRelease: 2014,
    carBodyType: 'Лімузин',
    seatsCount: '8 і більше',
    color: 'Жовтий',
    gearbox: 'Типтронік',
    driveType: 'Передній',
    fuelType: 'Бензин',
    varnishCoating: 'Професійно відремонтоварі сліди експлуатації',
    technicalCondition: [
      'Потребує кузовного ремонту',
      'Потребує ремонту ходової',
      'Сервісна книжка',
      'На ходу, технічно справна',
      'Гаражне зберігання',
    ],
    comfort: ['Кондиціонер', 'Омивач фар', 'Парктроник', 'Підсилювач керма'],
    multimedia: ['Акустика', 'AUX', 'CD', 'Bluetooth', 'CD', 'CD', 'Підсилювач'],
    security: [
      'Сигналізація',
      'ABS',
      'Броньований автомобіль',
      'Центральний замок',
      'Галогенні фари',
      'Центральний замок',
    ],
    photos: [32, 35, 33, 34, 37],
    user: 2,
    createdAt: 'Sat Nov 05 2011 09:27:40 GMT+0200 (за східноєвропейським стандартним часом)',
  },
  {
    title: 'sit et nisi consectetur aute',
    price: 1700000,
    status: 'АКТИВНЕ',
    category: 'Автобуси',
    subcategory: 'Lifan',
    carType: 'Під пригон (авто не в Україні)',
    mileage: 18467,
    сustomsСleared: 'Так',
    engineVolume: 2,
    theCarWasDrivenFrom: 'Португалія',
    model: 'eu et occaecat',
    yearOfRelease: 2024,
    carBodyType: 'Мінівен',
    seatsCount: '8 і більше',
    color: 'Коричневий',
    gearbox: 'Механічна',
    driveType: 'Задній',
    fuelType: 'Бензин',
    varnishCoating: 'Незначні сліди експлуатації (дрібні подряпини, сколи)',
    technicalCondition: ['Не пофарбована', 'Перший власник'],
    comfort: ['Люк', 'Електропакет', 'Панорамний дах'],
    multimedia: ['Система навігації GPS', 'AUX', 'Android Auto'],
    security: ['Подушка безпеки (Airbag)', 'Подушка безпеки (Airbag)'],
    photos: [32],
    user: 5,
    createdAt: 'Sat Dec 22 1979 14:15:44 GMT+0300 (за східноєвропейським стандартним часом)',
  },
  {
    title: 'id elit aliquip aliqua',
    price: 700000,
    status: 'АКТИВНЕ',
    category: 'Інший транспорт',
    subcategory: 'Land Rover',
    carType: 'Під пригон (авто не в Україні)',
    mileage: 48510,
    сustomsСleared: 'Так',
    engineVolume: 3,
    theCarWasDrivenFrom: 'Португалія',
    model: 'exercitation ullamco',
    yearOfRelease: 2016,
    carBodyType: 'Універсал',
    seatsCount: 4,
    color: 'Вишневий',
    gearbox: 'Варіатор',
    driveType: 'Повний',
    fuelType: 'Бензин',
    varnishCoating: "Не відремонтовані сліди експлуатації (подряпини, вм'ятини і т.д.)",
    technicalCondition: [
      'Потребує ремонту ходової',
      'Потребує ремонту двигуна',
      'Не на ходу',
      'Сервісна книжка',
      'Не на ходу',
    ],
    comfort: [
      'Люк',
      'Парктроник',
      'Електропакет',
      'Передня камера',
      "Бортовий комп'ютер",
      'Запуск кнопкою',
      'Підігрів сидінь',
      'Люк',
    ],
    multimedia: ['AUX'],
    security: [
      'LED фари',
      'Подушка безпеки (Airbag)',
      'ABD',
      'Замок на КПП',
      'ABD',
      'Пневмопідвіска',
      'Сигналізація',
      'Подушка безпеки (Airbag)',
    ],
    photos: [35, 33, 34, 33, 35],
    user: 6,
    createdAt: 'Sun Aug 24 1980 12:02:39 GMT+0300 (за східноєвропейським стандартним часом)',
  },
  {
    title: 'laboris ex elit culpa',
    price: 120000,
    status: 'НЕАКТИВНЕ',
    category: 'Мото',
    subcategory: 'Suzuki',
    carType: 'Під пригон (авто не в Україні)',
    mileage: 48510,
    сustomsСleared: 'Так',
    engineVolume: 6,
    theCarWasDrivenFrom: 'Бельгія',
    model: 'laborum',
    yearOfRelease: 2011,
    carBodyType: 'Купе',
    seatsCount: 5,
    color: 'Сірий',
    gearbox: 'Варіатор',
    driveType: 'Повний',
    fuelType: 'Інший',
    varnishCoating: 'Як нове, без видимих слідів експлуатації',
    technicalCondition: ['Перший власник', 'Не на ходу', 'Після ДТП', 'Не бита', 'Не пофарбована'],
    comfort: [
      'Камера заднього виду',
      'Парктроник',
      'Круїз контроль',
      'Клімат контроль',
      'Клімат контроль',
      'Датчик дощу',
    ],
    multimedia: ['Магнітола', 'Сабвуфер'],
    security: ['Пневмопідвіска', 'Сервокермо', 'ABD'],
    photos: [35, 36, 32, 34, 35],
    user: 6,
    createdAt: 'Sun Apr 14 2019 19:49:28 GMT+0300 (за східноєвропейським літнім часом)',
  },
  {
    title: 'adipisicing culpa non occaecat ut',
    price: 500000,
    status: 'ОЧІКУЄ ПІДТВЕРДЖЕННЯ',
    category: 'Мото',
    subcategory: 'Cadillac',
    carType: 'Під пригон (авто не в Україні)',
    mileage: 4271,
    сustomsСleared: 'Так',
    engineVolume: 1,
    theCarWasDrivenFrom: 'Латвія',
    model: 'sunt ea incididunt incididunt',
    yearOfRelease: 2021,
    carBodyType: 'Позашляховик / Кроссовер',
    seatsCount: '8 і більше',
    color: 'Білий',
    gearbox: 'Варіатор',
    driveType: 'Передній',
    fuelType: 'Гібрид',
    varnishCoating: 'Незначні сліди експлуатації (дрібні подряпини, сколи)',
    technicalCondition: ['На ходу, технічно справна', 'Не бита'],
    comfort: ["Пам'ять сидінь", "Пам'ять сидінь", 'Омивач фар', 'Електропакет'],
    multimedia: ['AUX', 'Android Auto'],
    security: ['Подушка безпеки (Airbag)', 'LED фари', 'Сигналізація', 'Сигналізація', 'Галогенні фари'],
    photos: [34, 36, 32, 33, 32, 35],
    user: 4,
    createdAt: 'Thu Aug 24 1972 23:38:07 GMT+0300 (за східноєвропейським стандартним часом)',
  },
  {
    title: 'exercitation mollit do ad ipsum anim',
    price: 1650000,
    status: 'НЕАКТИВНЕ',
    category: 'Легкові автомобілі',
    subcategory: 'Dodge',
    carType: 'З пробігом',
    mileage: 18467,
    сustomsСleared: 'Так',
    engineVolume: 7,
    theCarWasDrivenFrom: 'США',
    model: 'sunt officia adipisicing pariatur',
    yearOfRelease: 2014,
    carBodyType: 'Інший',
    seatsCount: 3,
    color: 'Чорний',
    gearbox: 'Адаптивна',
    driveType: 'Задній',
    fuelType: 'Гібрид',
    varnishCoating: 'Незначні сліди експлуатації (дрібні подряпини, сколи)',
    technicalCondition: ['Потребує кузовного ремонту', 'Гаражне зберігання', 'Потребує ремонту ходової', 'Не бита'],
    comfort: ['Клімат контроль', 'Омивач фар', 'Омивач фар', 'Омивач фар', 'Запуск кнопкою'],
    multimedia: ['Apple CarPay', 'Магнітола', 'Система навігації GPS', 'Bluetooth', 'Акустика'],
    security: [
      'Галогенні фари',
      'Сигналізація',
      'Замок на КПП',
      'Іммобілайзер',
      'Центральний замок',
      'Центральний замок',
      'Іммобілайзер',
    ],
    photos: [34, 35, 37],
    user: 3,
    createdAt: 'Sun Jul 30 1972 23:04:40 GMT+0300 (за східноєвропейським стандартним часом)',
  },
  {
    title: 'eu aliquip nulla ex dolor',
    price: 150000,
    status: 'АКТИВНЕ',
    category: 'Легкові автомобілі',
    subcategory: 'Aston Martin',
    carType: 'Під пригон (авто не в Україні)',
    mileage: 5849,
    сustomsСleared: 'Ні',
    engineVolume: 4,
    theCarWasDrivenFrom: 'Корея',
    model: 'eu qui',
    yearOfRelease: 2020,
    carBodyType: 'Седан',
    seatsCount: 6,
    color: 'Оливковий',
    gearbox: 'Механічна',
    driveType: 'Повний',
    fuelType: 'Дизель',
    varnishCoating: "Не відремонтовані сліди експлуатації (подряпини, вм'ятини і т.д.)",
    technicalCondition: ['Не бита'],
    comfort: [
      'Підігрів сидінь',
      'Обігрів керма',
      "Бортовий комп'ютер",
      'Підсилювач керма',
      "Бортовий комп'ютер",
      'Підігрів сидінь',
      'Клімат контроль',
      'Електропакет',
      'Запуск кнопкою',
    ],
    multimedia: ['USB', 'Сабвуфер', 'Сабвуфер', 'Система навігації GPS', 'USB', 'Bluetooth'],
    security: ['Лазерні фари', 'Броньований автомобіль', 'Іммобілайзер'],
    photos: [37, 35, 32, 32, 34, 34],
    user: 4,
    createdAt: 'Wed Oct 02 2002 15:23:19 GMT+0300 (за східноєвропейським літнім часом)',
  },
  {
    title: 'qui duis enim laborum Lorem ea pariatur reprehenderit',
    price: 150000,
    status: 'АКТИВНЕ',
    category: 'Мото',
    subcategory: 'Renault',
    carType: 'З пробігом',
    mileage: 47328,
    сustomsСleared: 'Ні',
    engineVolume: 1,
    theCarWasDrivenFrom: 'Литва',
    model: 'aute proident cupidatat eiusmod',
    yearOfRelease: 2016,
    carBodyType: 'Купе',
    seatsCount: 2,
    color: 'Фіолетовий',
    gearbox: 'Механічна',
    driveType: 'Передній',
    fuelType: 'Газ / бензин',
    varnishCoating: 'Як нове, без видимих слідів експлуатації',
    technicalCondition: ['Не на ходу', 'Потребує ремонту ходової'],
    comfort: [
      "Пам'ять сидінь",
      'Запуск кнопкою',
      "Бортовий комп'ютер",
      'Датчик світла',
      'Електропакет',
      "Бортовий комп'ютер",
    ],
    multimedia: [
      'Система навігації GPS',
      'Apple CarPay',
      'Apple CarPay',
      'Система навігації GPS',
      'Акустика',
      'Підсилювач',
      'Android Auto',
      'Підсилювач',
      'USB',
    ],
    security: ['Броньований автомобіль', 'Сервокермо'],
    photos: [37, 35, 37],
    user: 6,
    createdAt: 'Fri Aug 08 2008 02:23:12 GMT+0300 (за східноєвропейським літнім часом)',
  },
  {
    title: 'pariatur ad ut pariatur exercitation',
    price: 120000,
    status: 'АКТИВНЕ',
    category: 'Легкові автомобілі',
    subcategory: 'Lifan',
    carType: 'З пробігом',
    mileage: 47328,
    сustomsСleared: 'Так',
    engineVolume: 1,
    theCarWasDrivenFrom: 'Литва',
    model: 'aliquip do ad qui',
    yearOfRelease: 2018,
    carBodyType: 'Кабріолет',
    seatsCount: 2,
    color: 'Білий',
    gearbox: 'Адаптивна',
    driveType: 'Задній',
    fuelType: 'Інший',
    varnishCoating: "Не відремонтовані сліди експлуатації (подряпини, вм'ятини і т.д.)",
    technicalCondition: ['Потребує ремонту ходової', 'Сервісна книжка', 'Перший власник'],
    comfort: [
      'Передня камера',
      'Панорамний дах',
      'Круїз контроль',
      'Круїз контроль',
      'Тонування скла',
      'Електропакет',
      'Підсилювач керма',
      'Круїз контроль',
      'Датчик дощу',
    ],
    multimedia: ['Сабвуфер', 'Bluetooth', 'Акустика'],
    security: ['Лазерні фари', 'Центральний замок'],
    photos: [34, 32, 32, 34, 34, 33],
    user: 3,
    createdAt: 'Sat Apr 16 2022 02:26:11 GMT+0300 (за східноєвропейським літнім часом)',
  },
  {
    title: 'ut id dolore consequat duis nulla reprehenderit',
    price: 1650000,
    status: 'ОЧІКУЄ ПІДТВЕРДЖЕННЯ',
    category: 'Легкові автомобілі',
    subcategory: 'Rolls-Royse',
    carType: 'З пробігом',
    mileage: 1893,
    сustomsСleared: 'Ні',
    engineVolume: 3,
    theCarWasDrivenFrom: 'Литва',
    model: 'do',
    yearOfRelease: 2019,
    carBodyType: 'Мінівен',
    seatsCount: 3,
    color: 'Бежевий',
    gearbox: 'Автоматична',
    driveType: 'Задній',
    fuelType: 'Бензин',
    varnishCoating: 'Незначні сліди експлуатації (дрібні подряпини, сколи)',
    technicalCondition: ['Не на ходу', 'Не на ходу', 'Потребує кузовного ремонту', 'Не пофарбована', 'Сервісна книжка'],
    comfort: [
      'Алькантара',
      'Передня камера',
      'Ел. регулювання сидінь',
      'Шкіряний салон',
      "Пам'ять сидінь",
      "Бортовий комп'ютер",
    ],
    multimedia: ['Apple CarPay', 'Підсилювач', 'CD'],
    security: ['ESP', 'LED фари', 'Замок на КПП', 'Іммобілайзер', 'Сигналізація', 'ABS', 'Іммобілайзер'],
    photos: [34],
    user: 5,
    createdAt: 'Fri Sep 19 2014 16:56:30 GMT+0300 (за східноєвропейським літнім часом)',
  },
  {
    title: 'nulla duis veniam ex deserunt dolore nisi',
    price: 100000,
    status: 'АКТИВНЕ',
    category: 'Інший транспорт',
    subcategory: 'Honda',
    carType: 'Новий',
    mileage: 18467,
    сustomsСleared: 'Ні',
    engineVolume: 6,
    theCarWasDrivenFrom: 'Німеччина',
    model: 'eu sit consectetur',
    yearOfRelease: 2022,
    carBodyType: 'Пікап',
    seatsCount: '8 і більше',
    color: 'Оливковий',
    gearbox: 'Типтронік',
    driveType: 'Повний',
    fuelType: 'Газ / бензин',
    varnishCoating: 'Професійно відремонтоварі сліди експлуатації',
    technicalCondition: ['Не на ходу', 'Після ДТП'],
    comfort: [
      'Підігрів дзеркал',
      'Підігрів сидінь',
      "Пам'ять сидінь",
      'Парктроник',
      'Електросклопідйомники',
      'Обігрів керма',
      'Датчик дощу',
    ],
    multimedia: ['Підсилювач', 'Сабвуфер', 'Android Auto', 'Акустика', 'Магнітола', 'AUX'],
    security: ['Лазерні фари'],
    photos: [33, 34, 32, 36, 34],
    user: 5,
    createdAt: 'Mon Jun 27 1994 12:51:45 GMT+0300 (за східноєвропейським літнім часом)',
  },
  {
    title: 'occaecat fugiat elit officia eiusmod incididunt aliquip esse',
    price: 300000,
    status: 'НЕАКТИВНЕ',
    category: 'Автобуси',
    subcategory: 'Mercedes-Menz',
    carType: 'З пробігом',
    mileage: 4271,
    сustomsСleared: 'Ні',
    engineVolume: 6,
    theCarWasDrivenFrom: 'Іспанія',
    model: 'fugiat officia occaecat excepteur',
    yearOfRelease: 2018,
    carBodyType: 'Лімузин',
    seatsCount: '8 і більше',
    color: 'Інший',
    gearbox: 'Типтронік',
    driveType: 'Задній',
    fuelType: 'Бензин',
    varnishCoating: 'Незначні сліди експлуатації (дрібні подряпини, сколи)',
    technicalCondition: ['Сервісна книжка', 'Не на ходу', 'Після ДТП'],
    comfort: [
      'Підігрів дзеркал',
      'Клімат контроль',
      'Кондиціонер',
      'Круїз контроль',
      'Підігрів дзеркал',
      'Кондиціонер',
      'Електропакет',
      'Парктроник',
      'Датчик дощу',
    ],
    multimedia: ['CD', 'Apple CarPay', 'Акустика', 'AUX', 'Bluetooth', 'Apple CarPay', 'Apple CarPay'],
    security: [
      'ABD',
      'Іммобілайзер',
      'Іммобілайзер',
      'Сигналізація',
      'Лазерні фари',
      'Пневмопідвіска',
      'ABD',
      'LED фари',
      'LED фари',
      'Пневмопідвіска',
    ],
    photos: [34, 32, 33, 34],
    user: 2,
    createdAt: 'Wed Dec 16 2015 00:14:50 GMT+0200 (за східноєвропейським стандартним часом)',
  },
  {
    title: 'adipisicing et fugiat commodo',
    price: 5000000,
    status: 'АКТИВНЕ',
    category: 'Автобуси',
    subcategory: 'Lexus',
    carType: 'Новий',
    mileage: 2946,
    сustomsСleared: 'Так',
    engineVolume: 6,
    theCarWasDrivenFrom: 'Іспанія',
    model: 'consectetur',
    yearOfRelease: 2010,
    carBodyType: 'Лімузин',
    seatsCount: 3,
    color: 'Зелений',
    gearbox: 'Варіатор',
    driveType: 'Задній',
    fuelType: 'Газ / бензин',
    varnishCoating: "Не відремонтовані сліди експлуатації (подряпини, вм'ятини і т.д.)",
    technicalCondition: ['Потребує ремонту ходової', 'Не бита', 'Не пофарбована', 'Потребує ремонту двигуна'],
    comfort: ['Ел. регулювання сидінь'],
    multimedia: ['Сабвуфер', 'Apple CarPay', 'USB', 'USB', 'AUX'],
    security: [
      'Замок на КПП',
      'Іммобілайзер',
      'ABD',
      'Замок на КПП',
      'ABS',
      'ABS',
      'Галогенні фари',
      'Іммобілайзер',
      'Броньований автомобіль',
      'ABD',
    ],
    photos: [32, 37, 34, 36, 35, 35],
    user: 2,
    createdAt: 'Fri Apr 26 1991 17:20:42 GMT+0300 (за східноєвропейським літнім часом)',
  },
  {
    title: 'ex velit elit mollit Lorem consectetur ut velit',
    price: 150000,
    status: 'НЕАКТИВНЕ',
    category: 'Інший транспорт',
    subcategory: 'Tesla',
    carType: 'Під пригон (авто не в Україні)',
    mileage: 48561,
    сustomsСleared: 'Ні',
    engineVolume: 2,
    theCarWasDrivenFrom: 'Грузія',
    model: 'aliquip adipisicing dolor deserunt',
    yearOfRelease: 2016,
    carBodyType: 'Ліфтбек',
    seatsCount: 5,
    color: 'Зелений',
    gearbox: 'Автоматична',
    driveType: 'Передній',
    fuelType: 'Газ / бензин',
    varnishCoating: 'Як нове, без видимих слідів експлуатації',
    technicalCondition: ['Після ДТП'],
    comfort: ['Панорамний дах', 'Підігрів дзеркал', 'Підігрів дзеркал', 'Електросклопідйомники', 'Алькантара'],
    multimedia: ['Акустика', 'USB', 'CD'],
    security: ['Замок на КПП', 'Замок на КПП'],
    photos: [34],
    user: 6,
    createdAt: 'Fri Feb 05 1982 04:28:13 GMT+0300 (за східноєвропейським стандартним часом)',
  },
  {
    title: 'excepteur cupidatat excepteur quis',
    price: 1500000,
    status: 'НЕАКТИВНЕ',
    category: 'Інший транспорт',
    subcategory: 'Peugeot',
    carType: 'Новий',
    mileage: 47328,
    сustomsСleared: 'Ні',
    engineVolume: 1,
    theCarWasDrivenFrom: 'Корея',
    model: 'sunt sunt pariatur',
    yearOfRelease: 2022,
    carBodyType: 'Седан',
    seatsCount: 2,
    color: 'Вишневий',
    gearbox: 'Типтронік',
    driveType: 'Передній',
    fuelType: 'Дизель',
    varnishCoating: 'Як нове, без видимих слідів експлуатації',
    technicalCondition: [
      'Потребує ремонту двигуна',
      'Потребує ремонту ходової',
      'Не на ходу',
      'Потребує ремонту двигуна',
    ],
    comfort: ["Бортовий комп'ютер", 'Алькантара', 'Ел. регулювання сидінь', 'Парктроник'],
    multimedia: ['Магнітола', 'CD', 'Акустика'],
    security: ['Галогенні фари'],
    photos: [37, 34, 36],
    user: 7,
    createdAt: 'Fri Feb 21 2020 09:48:36 GMT+0200 (за східноєвропейським стандартним часом)',
  },
  {
    title: 'est excepteur sint ullamco fugiat ad est',
    price: 1750000,
    status: 'НЕАКТИВНЕ',
    category: 'Вантажні автомобілі',
    subcategory: 'Honda',
    carType: 'Новий',
    mileage: 18467,
    сustomsСleared: 'Так',
    engineVolume: 5,
    theCarWasDrivenFrom: 'Польша',
    model: 'nulla',
    yearOfRelease: 2014,
    carBodyType: 'Універсал',
    seatsCount: 2,
    color: 'Рожевий',
    gearbox: 'Механічна',
    driveType: 'Задній',
    fuelType: 'Гібрид',
    varnishCoating: 'Професійно відремонтоварі сліди експлуатації',
    technicalCondition: ['Не пофарбована', 'На ходу, технічно справна', 'Гаражне зберігання'],
    comfort: ['Парктроник', 'Люк'],
    multimedia: ['Акустика', 'Android Auto', 'Сабвуфер', 'Підсилювач', 'AUX', 'Підсилювач'],
    security: ['ABD', 'ABD', 'Замок на КПП', 'LED фари'],
    photos: [34, 36, 36],
    user: 3,
    createdAt: 'Tue Dec 13 1988 02:59:54 GMT+0300 (за східноєвропейським стандартним часом)',
  },
  {
    title: 'culpa dolor pariatur dolor eiusmod Lorem',
    price: 200000,
    status: 'НЕАКТИВНЕ',
    category: 'Мото',
    subcategory: 'Lexus',
    carType: 'Новий',
    mileage: 100,
    сustomsСleared: 'Ні',
    engineVolume: 4,
    theCarWasDrivenFrom: 'Польша',
    model: 'sit consectetur',
    yearOfRelease: 2014,
    carBodyType: 'Седан',
    seatsCount: 3,
    color: 'Золотистий',
    gearbox: 'Автоматична',
    driveType: 'Повний',
    fuelType: 'Інший',
    varnishCoating: 'Незначні сліди експлуатації (дрібні подряпини, сколи)',
    technicalCondition: ['На ходу, технічно справна', 'Не бита'],
    comfort: ['Підігрів дзеркал', 'Алькантара', 'Ел. регулювання сидінь'],
    multimedia: ['Android Auto', 'CD', 'Bluetooth', 'AUX', 'Bluetooth'],
    security: [
      'Іммобілайзер',
      'Галогенні фари',
      'Галогенні фари',
      'ESP',
      'ABS',
      'Центральний замок',
      'Броньований автомобіль',
      'Сигналізація',
      'LED фари',
    ],
    photos: [33, 37, 36, 32, 37],
    user: 5,
    createdAt: 'Wed Dec 25 2019 00:06:42 GMT+0200 (за східноєвропейським стандартним часом)',
  },
  {
    title: 'consequat reprehenderit velit ea laborum sint in et',
    price: 300000,
    status: 'ОЧІКУЄ ПІДТВЕРДЖЕННЯ',
    category: 'Вантажні автомобілі',
    subcategory: 'Rover',
    carType: 'Під пригон (авто не в Україні)',
    mileage: 2946,
    сustomsСleared: 'Ні',
    engineVolume: 1,
    theCarWasDrivenFrom: 'Іспанія',
    model: 'Lorem ullamco commodo nulla',
    yearOfRelease: 2011,
    carBodyType: 'Інший',
    seatsCount: 2,
    color: 'Сірий',
    gearbox: 'Механічна',
    driveType: 'Повний',
    fuelType: 'Бензин',
    varnishCoating: "Не відремонтовані сліди експлуатації (подряпини, вм'ятини і т.д.)",
    technicalCondition: ['Перший власник', 'Не на ходу'],
    comfort: ['Обігрів керма', 'Запуск кнопкою'],
    multimedia: ['USB', 'Система навігації GPS', 'Android Auto', 'Сабвуфер', 'AUX', 'Сабвуфер', 'Магнітола'],
    security: ['LED фари', 'Галогенні фари', 'Замок на КПП', 'Пневмопідвіска'],
    photos: [32, 33],
    user: 7,
    createdAt: 'Wed Dec 30 1981 20:11:14 GMT+0300 (за східноєвропейським стандартним часом)',
  },
  {
    title: 'dolor nisi culpa ut reprehenderit',
    price: 500000,
    status: 'ОЧІКУЄ ПІДТВЕРДЖЕННЯ',
    category: 'Легкові автомобілі',
    subcategory: 'Chrysler',
    carType: 'З пробігом',
    mileage: 18467,
    сustomsСleared: 'Так',
    engineVolume: 5,
    theCarWasDrivenFrom: 'Молдова',
    model: 'voluptate',
    yearOfRelease: 2012,
    carBodyType: 'Інший',
    seatsCount: 6,
    color: 'Матовий',
    gearbox: 'Механічна',
    driveType: 'Задній',
    fuelType: 'Бензин',
    varnishCoating: 'Незначні сліди експлуатації (дрібні подряпини, сколи)',
    technicalCondition: ['Не пофарбована'],
    comfort: ['Тонування скла', 'Алькантара'],
    multimedia: [
      'Сабвуфер',
      'CD',
      'Підсилювач',
      'USB',
      'AUX',
      'Apple CarPay',
      'Система навігації GPS',
      'Система навігації GPS',
      'Apple CarPay',
    ],
    security: [
      'LED фари',
      'Сервокермо',
      'Центральний замок',
      'Пневмопідвіска',
      'Замок на КПП',
      'Лазерні фари',
      'Подушка безпеки (Airbag)',
      'Центральний замок',
      'Лазерні фари',
    ],
    photos: [34, 33, 36, 37, 36],
    user: 3,
    createdAt: 'Sat Apr 16 2011 07:13:19 GMT+0300 (за східноєвропейським літнім часом)',
  },
  {
    title: 'duis cupidatat tempor culpa',
    price: 120000,
    status: 'АКТИВНЕ',
    category: 'Вантажні автомобілі',
    subcategory: 'Lexus',
    carType: 'Під пригон (авто не в Україні)',
    mileage: 586,
    сustomsСleared: 'Ні',
    engineVolume: 1,
    theCarWasDrivenFrom: 'Грузія',
    model: 'sunt velit',
    yearOfRelease: 2014,
    carBodyType: 'Лімузин',
    seatsCount: 2,
    color: 'Зелений',
    gearbox: 'Варіатор',
    driveType: 'Повний',
    fuelType: 'Бензин',
    varnishCoating: 'Потрібно відновлення (фарбування, заміна деталей, зварювання)',
    technicalCondition: ['Сервісна книжка', 'Потребує ремонту двигуна', 'Потребує кузовного ремонту', 'Після ДТП'],
    comfort: [
      'Датчик дощу',
      'Тонування скла',
      'Підігрів сидінь',
      'Шкіряний салон',
      'Підігрів дзеркал',
      'Запуск кнопкою',
      'Тонування скла',
      "Пам'ять сидінь",
    ],
    multimedia: ['Apple CarPay', 'Магнітола', 'AUX', 'Акустика', 'Акустика', 'Bluetooth', 'CD', 'Apple CarPay'],
    security: [
      'ABS',
      'Подушка безпеки (Airbag)',
      'Сервокермо',
      'Пневмопідвіска',
      'Іммобілайзер',
      'Центральний замок',
      'ABD',
      'Подушка безпеки (Airbag)',
    ],
    photos: [33, 34, 32, 35, 37],
    user: 3,
    createdAt: 'Mon Nov 05 2007 14:38:35 GMT+0200 (за східноєвропейським стандартним часом)',
  },
  {
    title: 'dolor occaecat ipsum in',
    price: 1750000,
    status: 'АКТИВНЕ',
    category: 'Автобуси',
    subcategory: 'Huyndai',
    carType: 'Під пригон (авто не в Україні)',
    mileage: 100,
    сustomsСleared: 'Так',
    engineVolume: 3,
    theCarWasDrivenFrom: 'Швейцарія',
    model: 'ullamco',
    yearOfRelease: 2010,
    carBodyType: 'Хетчбек',
    seatsCount: 6,
    color: 'Коричневий',
    gearbox: 'Типтронік',
    driveType: 'Передній',
    fuelType: 'Бензин',
    varnishCoating: 'Професійно відремонтоварі сліди експлуатації',
    technicalCondition: ['Не бита'],
    comfort: [
      'Камера заднього виду',
      'Підсилювач керма',
      'Датчик дощу',
      'Електропакет',
      'Камера заднього виду',
      "Бортовий комп'ютер",
      'Обігрів керма',
      'Шкіряний салон',
    ],
    multimedia: ['Apple CarPay', 'Акустика', 'CD', 'Bluetooth'],
    security: ['ABD', 'Лазерні фари'],
    photos: [32, 34, 32, 36],
    user: 5,
    createdAt: 'Tue Mar 18 2003 05:51:56 GMT+0200 (за східноєвропейським стандартним часом)',
  },
  {
    title: 'qui ullamco id sunt',
    price: 1700000,
    status: 'ОЧІКУЄ ПІДТВЕРДЖЕННЯ',
    category: 'Мото',
    subcategory: 'Jaguar',
    carType: 'Під пригон (авто не в Україні)',
    mileage: 5849,
    сustomsСleared: 'Так',
    engineVolume: 2,
    theCarWasDrivenFrom: 'Литва',
    model: 'deserunt cupidatat',
    yearOfRelease: 2015,
    carBodyType: 'Інший',
    seatsCount: '8 і більше',
    color: 'Золотистий',
    gearbox: 'Типтронік',
    driveType: 'Задній',
    fuelType: 'Дизель',
    varnishCoating: "Не відремонтовані сліди експлуатації (подряпини, вм'ятини і т.д.)",
    technicalCondition: ['Не бита'],
    comfort: ['Передня камера', 'Омивач фар', 'Передня камера'],
    multimedia: ['Bluetooth', 'Підсилювач', 'CD', 'Bluetooth', 'Магнітола', 'Android Auto', 'Акустика'],
    security: ['Лазерні фари'],
    photos: [36],
    user: 5,
    createdAt: 'Thu Nov 11 1999 15:33:28 GMT+0200 (за східноєвропейським стандартним часом)',
  },
  {
    title: 'sunt occaecat eiusmod sunt deserunt eu ea',
    price: 1700000,
    status: 'ОЧІКУЄ ПІДТВЕРДЖЕННЯ',
    category: 'Мото',
    subcategory: 'Jaguar',
    carType: 'Під пригон (авто не в Україні)',
    mileage: 18467,
    сustomsСleared: 'Ні',
    engineVolume: 1,
    theCarWasDrivenFrom: 'Молдова',
    model: 'excepteur ea incididunt dolor',
    yearOfRelease: 2021,
    carBodyType: 'Кабріолет',
    seatsCount: 2,
    color: 'Золотистий',
    gearbox: 'Автоматична',
    driveType: 'Передній',
    fuelType: 'Гібрид',
    varnishCoating: 'Потрібно відновлення (фарбування, заміна деталей, зварювання)',
    technicalCondition: ['Не на ходу', 'Не на ходу', 'Потребує ремонту двигуна'],
    comfort: ['Круїз контроль'],
    multimedia: ['Система навігації GPS'],
    security: ['ABD', 'Іммобілайзер', 'Замок на КПП'],
    photos: [35, 33, 35],
    user: 7,
    createdAt: 'Mon Sep 15 1975 15:55:11 GMT+0300 (за східноєвропейським стандартним часом)',
  },
  {
    title: 'aute occaecat enim amet',
    price: 120000,
    status: 'АКТИВНЕ',
    category: 'Вантажні автомобілі',
    subcategory: 'Jaguar',
    carType: 'З пробігом',
    mileage: 47328,
    сustomsСleared: 'Так',
    engineVolume: 4,
    theCarWasDrivenFrom: 'Франція',
    model: 'deserunt',
    yearOfRelease: 2021,
    carBodyType: 'Пікап',
    seatsCount: 6,
    color: 'Чорний',
    gearbox: 'Механічна',
    driveType: 'Передній',
    fuelType: 'Інший',
    varnishCoating: 'Потрібно відновлення (фарбування, заміна деталей, зварювання)',
    technicalCondition: ['Потребує кузовного ремонту', 'Після ДТП'],
    comfort: ['Датчик дощу', 'Підігрів дзеркал', 'Люк', "Пам'ять сидінь", 'Шкіряний салон'],
    multimedia: ['AUX', 'CD', 'Підсилювач', 'Сабвуфер', 'Android Auto', 'CD', 'Bluetooth', 'Bluetooth'],
    security: ['LED фари', 'ABD', 'Замок на КПП', 'Сервокермо', 'ABS', 'Галогенні фари'],
    photos: [37, 33, 37, 33, 32, 36],
    user: 3,
    createdAt: 'Fri Feb 16 1996 12:04:40 GMT+0200 (за східноєвропейським стандартним часом)',
  },
  {
    title: 'veniam aliqua mollit ipsum deserunt',
    price: 800000,
    status: 'АКТИВНЕ',
    category: 'Мото',
    subcategory: 'Skoda',
    carType: 'Новий',
    mileage: 48510,
    сustomsСleared: 'Ні',
    engineVolume: 3,
    theCarWasDrivenFrom: 'Корея',
    model: 'et voluptate excepteur',
    yearOfRelease: 2016,
    carBodyType: 'Позашляховик / Кроссовер',
    seatsCount: 4,
    color: 'Зелений',
    gearbox: 'Типтронік',
    driveType: 'Повний',
    fuelType: 'Дизель',
    varnishCoating: 'Професійно відремонтоварі сліди експлуатації',
    technicalCondition: ['Не пофарбована', 'Сервісна книжка'],
    comfort: ['Парктроник', 'Алькантара', 'Кондиціонер'],
    multimedia: [
      'Система навігації GPS',
      'CD',
      'CD',
      'Система навігації GPS',
      'Магнітола',
      'Підсилювач',
      'Android Auto',
      'Android Auto',
      'Магнітола',
    ],
    security: [
      'Галогенні фари',
      'Броньований автомобіль',
      'ABS',
      'Галогенні фари',
      'ABD',
      'Галогенні фари',
      'Сервокермо',
    ],
    photos: [33, 32, 35, 37, 36, 33],
    user: 7,
    createdAt: 'Mon Oct 02 2017 18:20:44 GMT+0300 (за східноєвропейським літнім часом)',
  },
  {
    title: 'veniam nostrud laborum aute',
    price: 700000,
    status: 'НЕАКТИВНЕ',
    category: 'Автобуси',
    subcategory: 'Renault',
    carType: 'Під пригон (авто не в Україні)',
    mileage: 2946,
    сustomsСleared: 'Ні',
    engineVolume: 2,
    theCarWasDrivenFrom: 'Корея',
    model: 'magna dolor tempor est',
    yearOfRelease: 2016,
    carBodyType: 'Кабріолет',
    seatsCount: 3,
    color: 'Зелений',
    gearbox: 'Адаптивна',
    driveType: 'Передній',
    fuelType: 'Інший',
    varnishCoating: "Не відремонтовані сліди експлуатації (подряпини, вм'ятини і т.д.)",
    technicalCondition: ['Не на ходу', 'Сервісна книжка', 'Після ДТП', 'Сервісна книжка'],
    comfort: [
      "Пам'ять сидінь",
      'Мультируль',
      "Бортовий комп'ютер",
      'Омивач фар',
      'Ел. регулювання сидінь',
      'Датчик світла',
    ],
    multimedia: ['Android Auto', 'AUX', 'Підсилювач', 'Магнітола', 'Apple CarPay', 'CD'],
    security: [
      'Пневмопідвіска',
      'Подушка безпеки (Airbag)',
      'Сервокермо',
      'Центральний замок',
      'Подушка безпеки (Airbag)',
      'ABD',
      'Лазерні фари',
      'ESP',
      'Пневмопідвіска',
      'Подушка безпеки (Airbag)',
    ],
    photos: [33, 35, 34, 32, 32, 36],
    user: 5,
    createdAt: 'Thu Sep 27 1984 00:47:23 GMT+0400 (за східноєвропейським літнім часом)',
  },
  {
    title: 'aliqua excepteur sint excepteur cillum consequat',
    price: 300000,
    status: 'АКТИВНЕ',
    category: 'Мото',
    subcategory: 'Toyota',
    carType: 'З пробігом',
    mileage: 5849,
    сustomsСleared: 'Так',
    engineVolume: 6,
    theCarWasDrivenFrom: 'Італія',
    model: 'duis enim cupidatat in',
    yearOfRelease: 2015,
    carBodyType: 'Седан',
    seatsCount: '8 і більше',
    color: 'Коричневий',
    gearbox: 'Типтронік',
    driveType: 'Передній',
    fuelType: 'Газ / бензин',
    varnishCoating: 'Потрібно відновлення (фарбування, заміна деталей, зварювання)',
    technicalCondition: ['Після ДТП', 'Не пофарбована', 'Не на ходу', 'Потребує ремонту двигуна'],
    comfort: ['Тонування скла', "Пам'ять сидінь", 'Люк'],
    multimedia: ['Apple CarPay', 'AUX', 'Android Auto', 'Магнітола', 'Сабвуфер'],
    security: [
      'Подушка безпеки (Airbag)',
      'Подушка безпеки (Airbag)',
      'Центральний замок',
      'ABD',
      'Лазерні фари',
      'ABS',
      'Лазерні фари',
      'Іммобілайзер',
      'Галогенні фари',
      'Іммобілайзер',
    ],
    photos: [33, 36, 37, 37, 32, 33],
    user: 7,
    createdAt: 'Thu Jan 16 2014 07:08:49 GMT+0200 (за східноєвропейським стандартним часом)',
  },
  {
    title: 'ea exercitation commodo excepteur enim',
    price: 1750000,
    status: 'ОЧІКУЄ ПІДТВЕРДЖЕННЯ',
    category: 'Мото',
    subcategory: 'Jeep',
    carType: 'Під пригон (авто не в Україні)',
    mileage: 5849,
    сustomsСleared: 'Так',
    engineVolume: 2,
    theCarWasDrivenFrom: 'Франція',
    model: 'cupidatat',
    yearOfRelease: 2016,
    carBodyType: 'Купе',
    seatsCount: 5,
    color: 'Зелений',
    gearbox: 'Автоматична',
    driveType: 'Задній',
    fuelType: 'Електро',
    varnishCoating: 'Як нове, без видимих слідів експлуатації',
    technicalCondition: ['Не бита', 'Потребує кузовного ремонту', 'Не бита', 'Сервісна книжка'],
    comfort: ['Підігрів дзеркал', 'Підігрів дзеркал', 'Датчик світла', 'Парктроник'],
    multimedia: ['CD', 'Bluetooth', 'AUX', 'Підсилювач'],
    security: ['Замок на КПП', 'Галогенні фари'],
    photos: [37, 35, 34, 32, 34, 32],
    user: 3,
    createdAt: 'Mon Feb 27 2006 04:09:47 GMT+0200 (за східноєвропейським стандартним часом)',
  },
  {
    title: 'reprehenderit sunt ut aute commodo cillum elit',
    price: 800000,
    status: 'АКТИВНЕ',
    category: 'Вантажні автомобілі',
    subcategory: 'Mitsubishi',
    carType: 'З пробігом',
    mileage: 47328,
    сustomsСleared: 'Ні',
    engineVolume: 5,
    theCarWasDrivenFrom: 'Франція',
    model: 'cupidatat',
    yearOfRelease: 2015,
    carBodyType: 'Універсал',
    seatsCount: 2,
    color: 'Бежевий',
    gearbox: 'Автоматична',
    driveType: 'Передній',
    fuelType: 'Газ / бензин',
    varnishCoating: "Не відремонтовані сліди експлуатації (подряпини, вм'ятини і т.д.)",
    technicalCondition: ['Після ДТП', 'Не бита', 'Після ДТП', 'На ходу, технічно справна'],
    comfort: [
      'Люк',
      'Датчик світла',
      'Обігрів керма',
      "Пам'ять сидінь",
      'Кондиціонер',
      'Електросклопідйомники',
      'Датчик дощу',
    ],
    multimedia: ['Apple CarPay', 'AUX', 'Сабвуфер', 'Сабвуфер', 'Підсилювач', 'CD'],
    security: [
      'Центральний замок',
      'Броньований автомобіль',
      'ESP',
      'Замок на КПП',
      'ESP',
      'LED фари',
      'Галогенні фари',
      'Сигналізація',
      'Галогенні фари',
      'Сигналізація',
    ],
    photos: [32, 37, 32],
    user: 4,
    createdAt: 'Sat Apr 12 1997 08:46:20 GMT+0300 (за східноєвропейським літнім часом)',
  },
  {
    title: 'magna esse dolore exercitation laborum quis',
    price: 2300000,
    status: 'АКТИВНЕ',
    category: 'Вантажні автомобілі',
    subcategory: 'Geely',
    carType: 'З пробігом',
    mileage: 18467,
    сustomsСleared: 'Ні',
    engineVolume: 3,
    theCarWasDrivenFrom: 'Франція',
    model: 'nulla irure ipsum',
    yearOfRelease: 2011,
    carBodyType: 'Пікап',
    seatsCount: 3,
    color: 'Коричневий',
    gearbox: 'Варіатор',
    driveType: 'Передній',
    fuelType: 'Газ / бензин',
    varnishCoating: "Не відремонтовані сліди експлуатації (подряпини, вм'ятини і т.д.)",
    technicalCondition: [
      'Не пофарбована',
      'Не пофарбована',
      'Потребує кузовного ремонту',
      'Перший власник',
      'Потребує кузовного ремонту',
    ],
    comfort: [
      'Круїз контроль',
      'Люк',
      'Мультируль',
      'Підсилювач керма',
      'Тонування скла',
      "Пам'ять сидінь",
      'Ел. регулювання сидінь',
      'Омивач фар',
      'Запуск кнопкою',
    ],
    multimedia: ['Android Auto', 'Акустика'],
    security: ['Галогенні фари', 'Подушка безпеки (Airbag)', 'Броньований автомобіль', 'Сигналізація', 'ESP'],
    photos: [35, 33, 37],
    user: 2,
    createdAt: 'Fri Mar 15 1996 19:01:20 GMT+0200 (за східноєвропейським стандартним часом)',
  },
  {
    title: 'sunt elit sint fugiat est consectetur deserunt ea',
    price: 3000000,
    status: 'ОЧІКУЄ ПІДТВЕРДЖЕННЯ',
    category: 'Легкові автомобілі',
    subcategory: 'Bentley',
    carType: 'З пробігом',
    mileage: 3721,
    сustomsСleared: 'Ні',
    engineVolume: 6,
    theCarWasDrivenFrom: 'Швейцарія',
    model: 'ipsum cupidatat esse velit',
    yearOfRelease: 2023,
    carBodyType: 'Універсал',
    seatsCount: 3,
    color: 'Синій',
    gearbox: 'Адаптивна',
    driveType: 'Задній',
    fuelType: 'Інший',
    varnishCoating: 'Потрібно відновлення (фарбування, заміна деталей, зварювання)',
    technicalCondition: ['Не бита', 'Не пофарбована'],
    comfort: [
      'Запуск кнопкою',
      'Запуск кнопкою',
      'Омивач фар',
      'Датчик світла',
      'Камера заднього виду',
      "Пам'ять сидінь",
      'Клімат контроль',
      'Ел. регулювання сидінь',
      "Бортовий комп'ютер",
      'Підсилювач керма',
    ],
    multimedia: ['CD'],
    security: ['Подушка безпеки (Airbag)'],
    photos: [32],
    user: 7,
    createdAt: 'Wed Aug 22 2012 00:36:09 GMT+0300 (за східноєвропейським літнім часом)',
  },
  {
    title: 'proident nulla enim laborum sit proident duis proident',
    price: 500000,
    status: 'АКТИВНЕ',
    category: 'Мото',
    subcategory: 'Peugeot',
    carType: 'Під пригон (авто не в Україні)',
    mileage: 100,
    сustomsСleared: 'Ні',
    engineVolume: 2,
    theCarWasDrivenFrom: 'Латвія',
    model: 'quis excepteur consectetur minim',
    yearOfRelease: 2019,
    carBodyType: 'Універсал',
    seatsCount: 4,
    color: 'Зелений',
    gearbox: 'Механічна',
    driveType: 'Задній',
    fuelType: 'Гібрид',
    varnishCoating: 'Потрібно відновлення (фарбування, заміна деталей, зварювання)',
    technicalCondition: ['Потребує ремонту двигуна'],
    comfort: ['Ел. регулювання сидінь', 'Електросклопідйомники'],
    multimedia: ['Підсилювач', 'Магнітола'],
    security: ['ABS', 'Сигналізація', 'Сервокермо'],
    photos: [32],
    user: 4,
    createdAt: 'Tue Jan 26 2016 03:14:08 GMT+0200 (за східноєвропейським стандартним часом)',
  },
  {
    title: 'minim commodo ex in incididunt culpa',
    price: 120000,
    status: 'НЕАКТИВНЕ',
    category: 'Легкові автомобілі',
    subcategory: 'Volvo',
    carType: 'Під пригон (авто не в Україні)',
    mileage: 3721,
    сustomsСleared: 'Так',
    engineVolume: 1,
    theCarWasDrivenFrom: 'Корея',
    model: 'ut Lorem laborum',
    yearOfRelease: 2018,
    carBodyType: 'Купе',
    seatsCount: '8 і більше',
    color: 'Жовтий',
    gearbox: 'Автоматична',
    driveType: 'Задній',
    fuelType: 'Газ / бензин',
    varnishCoating: 'Як нове, без видимих слідів експлуатації',
    technicalCondition: [
      'Сервісна книжка',
      'Потребує ремонту двигуна',
      'Потребує ремонту двигуна',
      'Не бита',
      'Після ДТП',
    ],
    comfort: ['Датчик світла', 'Шкіряний салон'],
    multimedia: ['Bluetooth', 'Apple CarPay', 'CD', 'Система навігації GPS', 'AUX'],
    security: [
      'Іммобілайзер',
      'Броньований автомобіль',
      'ABD',
      'Подушка безпеки (Airbag)',
      'Центральний замок',
      'Замок на КПП',
    ],
    photos: [34, 34, 37, 36, 32],
    user: 6,
    createdAt: 'Sat Aug 20 1988 19:09:13 GMT+0400 (за східноєвропейським літнім часом)',
  },
  {
    title: 'irure eiusmod nostrud id',
    price: 200000,
    status: 'НЕАКТИВНЕ',
    category: 'Інший транспорт',
    subcategory: 'Skoda',
    carType: 'З пробігом',
    mileage: 3721,
    сustomsСleared: 'Так',
    engineVolume: 2,
    theCarWasDrivenFrom: 'Грузія',
    model: 'ut culpa sit',
    yearOfRelease: 2023,
    carBodyType: 'Седан',
    seatsCount: 6,
    color: 'Червоний',
    gearbox: 'Типтронік',
    driveType: 'Задній',
    fuelType: 'Інший',
    varnishCoating: 'Потрібно відновлення (фарбування, заміна деталей, зварювання)',
    technicalCondition: ['Після ДТП', 'Гаражне зберігання', 'Потребує кузовного ремонту', 'Не пофарбована'],
    comfort: ['Електросклопідйомники', 'Підігрів сидінь', 'Кондиціонер', 'Підсилювач керма', "Пам'ять сидінь"],
    multimedia: ['Акустика', 'Магнітола', 'Android Auto', 'CD'],
    security: ['Центральний замок', 'Центральний замок', 'Подушка безпеки (Airbag)'],
    photos: [36],
    user: 4,
    createdAt: 'Sun Apr 05 2020 01:31:18 GMT+0300 (за східноєвропейським літнім часом)',
  },
]

/* 
https://json-generator.com/


[
  '{{repeat(4, 10)}}',
  {
    ,
    title: '{{lorem([random(4, 5, 6, 7, 8)], "words")}}',
    price: '{{random(100000, 120000, 150000, 200000, 300000, 500000, 700000, 800000,1000000,1200000,1500000,1650000,1700000,1750000,2000000,2300000,3000000,5000000)}}',
    status: '{{random("ОЧІКУЄ ПІДТВЕРДЖЕННЯ","АКТИВНЕ","НЕАКТИВНЕ")}}',
    category: '{{random("Легкові автомобілі", "Вантажні автомобілі", "Автобуси", "Мото", "Інший транспорт")}}',
    subcategory: '{{random("Acura", "Alfa Romeo", "Aston Martin", "Audi", "Bentley", "BMW", "Buick", "Cadillac", "Chana", "Chery", "Chevrolet", "Chrysler", "Citroen", "Dacia", "Daewoo", "Dodge", "Ferrari", "Fiat", "Ford", "Geely", "Honda", "Hummer", "Huyndai", "Infinity", "Jaguar", "Jeep", "Kia", "Lamborghini", "Land Rover", "Lexus", "Lifan", "Lincoln", "Maserati", "Maybach", "Mazda", "McLaren", "Mercedes-Menz", "Mitsubishi", "Nissan", "Opel", "Peugeot", "Porsche", "Renault", "Rolls-Royse", "Rover", "Skoda", "Subaru", "Suzuki", "Tesla", "Toyota", "Volkswagen", "Volvo", "Інші")}}',
    carType: '{{random("З пробігом", "Новий", "Під пригон (авто не в Україні)")}}',
    mileage: '{{random("100", "2946", "5849", "95978", "48561", "4271", "3721", "586", "47328", "18467", "48510", "1893", "2834")}}',
    сustomsСleared: '{{random("Так", "Ні")}}',
    engineVolume: '{{random(1, 2, 3, 4, 5, 6, 7)}}',
    theCarWasDrivenFrom: '{{random("США", "Німеччина", "Литва", "Грузія", "Корея", "Польша", "Швейцарія", "Норвегія", "Франція", "Молдова", "Іспанія", "Італія", "Португалія", "Нідерланди" , "Бельгія" , "Латвія" , "Інша країна")}}',
    model: '{{lorem([random(1, 2, 3, 4)], "words")}}',
    yearOfRelease: '{{random("2012", "2015", "2016", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2010", "2011", "2014")}}',
    carBodyType: '{{random("Кабріолет", "Пікап", "Купе", "Універсал", "Хетчбек", "Мінівен", "Позашляховик / Кроссовер", "Седан", "Ліфтбек", "Лімузин", "Інший")}}',
    seatsCount: '{{random("2", "3", "4", "5", "6", "8 і більше")}}',
    color: '{{random("Білий", "Чорний", "Синій", "Сірий", "Сріблястий", "Червоний", "Зелений", "Бежевий", "Бірюзовий", "Бронзовий", "Вишневий", "Блакитний", "Жовтий", "Золотистий", "Коричневий", "Матовий", "Оливковий", "Рожевий", "Фіолетовий", "Інший")}}',
    gearbox: '{{random("Механічна", "Автоматична", "Варіатор", "Адаптивна", "Типтронік")}}',
    driveType: '{{random("Повний", "Передній", "Задній")}}',
    fuelType: '{{random("Бензин", "Дизель", "Газ / бензин", "Електро", "Гібрид", "Інший")}}',
    varnishCoating: '{{random("Як нове, без видимих слідів експлуатації", "Професійно відремонтоварі сліди експлуатації", "Незначні сліди експлуатації (дрібні подряпини, сколи)", "Не відремонтовані сліди експлуатації (подряпини, вм\'ятини і т.д.)", "Потрібно відновлення (фарбування, заміна деталей, зварювання)")}}',
    technicalCondition: [
      '{{repeat(1, 5)}}',
      '{{random("На ходу, технічно справна", "Не бита", "Не пофарбована", "Гаражне зберігання", "Перший власник", "Сервісна книжка", "Потребує кузовного ремонту", "Потребує ремонту ходової", "Потребує ремонту двигуна", "Після ДТП", "Не на ходу")}}'
    ],
    comfort: [
      '{{repeat(1, 10)}}',
      '{{random("Електропакет", "Електросклопідйомники", "Кондиціонер", "Парктроник", "Бортовий комп\'ютер", "Датчик світла", "Запуск кнопкою", "Клімат контроль", "Шкіряний салон", "Круїз контроль", "Люк", "Панорамний дах", "Ел. регулювання сидінь", "Камера заднього виду", "Передня камера", "Мультируль", "Омивач фар", "Підігрів дзеркал", "Обігрів керма", "Підсилювач керма", "Підігрів сидінь", "Тонування скла", "Пам\'ять сидінь", "Датчик дощу", "Алькантара")}}'
    ],
    multimedia: [
      '{{repeat(1, 10)}}',
      '{{random("CD", "AUX", "Bluetooth", "USB", "Акустика", "Магнітола", "Підсилювач", "Сабвуфер", "Система навігації GPS", "Apple CarPay", "Android Auto")}}'
    ],
    security: [
      '{{repeat(1, 10)}}',
      '{{random("ABD", "ABS", "ESP", "Броньований автомобіль", "Галогенні фари", "Замок на КПП", "Іммобілайзер", "Пневмопідвіска", "Подушка безпеки (Airbag)", "Сервокермо", "Сигналізація", "Центральний замок", "LED фари", "Лазерні фари")}}'
    ],
    photos: [
      '{{repeat(1, 6)}}'
      '{{random(23, 24, 25, 26, 27, 28, 29, 30, 31)}}'
    ],
    user: user: '{{random(2, 3, 4, 5, 6, 7)}}',,
    createdAt: '{{date()}}'
  }
]
*/
